The-Commit-Company/raven

raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/utils/operations.ts

changed date format to current time instead of time ago

---

raven-app/src/components/layout/Heading/PageHeader.tsx
raven-app/src/components/layout/Sidebar/Sidebar.tsx

54 add logout button

---

raven/hooks.py
raven/permissions.py
raven/raven_channel_management/doctype/raven_channel/raven_channel.json
raven/raven_channel_management/doctype/raven_channel/raven_channel.py
raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py
raven/raven_messaging/doctype/raven_message/raven_message.py

62 enforce user permissions for messages

---

raven/fixtures/raven_channel.json

Fixtures create default data on app install
Closes #52

feat: added fixture for general channel

---

raven-app/src/components/feature/channels/DirectMessageList.tsx

fix: do not show Guest in direct messages

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/types/Messaging/Message.ts
raven/raven_messaging/doctype/raven_message/raven_message.json

added view, download for image, file message types

63 add support for file messages

---

raven-app/src/components/feature/chat/ChatInput.tsx

Revert "fixed: part of the problem"

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatInput.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/chat/styles.css
raven-app/src/components/feature/file-upload/FileListItem.tsx

1. file list view grid fixed (it was going out of bounds before when more than 4 files got uploaded)
2. trailing newline in text messages is removed
3. chat interface design made responsive

59 user references should be highlighted

---

raven-app/src/components/feature/channels/ChannelList.tsx
raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/components/feature/user-details/UserProfileDrawer.tsx

1. open user details drawer when user name is clicked in the chat space

129 show user profile info when clicked on user name

---

raven-app/src/components/feature/channels/DirectMessageList.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/user-details/UserProfileDrawer.tsx
raven-app/src/types/User/User.ts
raven-app/src/utils/channel/ChannelProvider.tsx
raven-app/src/utils/operations.ts
raven-app/src/utils/user/UserDataProvider.tsx
raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py

- added online-status indicator (green dot) to DM list and chat header
- added availability status and current time to user-profile-drawer
- added functionality to message user from user-profile-drawer

feat: added user online status

---

raven-app/src/components/feature/channels/ViewChannelDetailsModal.tsx
raven-app/src/components/feature/files/FilesSharedInChannel.tsx
raven/raven_messaging/doctype/raven_message/raven_message.py

added recent shared files tab in channel details

---

raven-app/package.json
raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/components/feature/file-preview/ImagePreviewModal.tsx
raven-app/src/components/feature/file-preview/ImageViewer.tsx
raven-app/yarn.lock

144 image full preview and download

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/types/Messaging/Message.ts

153 separate text messages sent within 2 minutes by the same user should be shown together

---

raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/components/feature/file-preview/PDFPreviewModal.tsx
raven-app/src/components/feature/markdown-viewer/MarkdownRenderer.css

162 add modal to view pdf files

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/chat/ChatMessage.tsx
raven-app/src/components/feature/global-search/FileSearch.tsx
raven-app/src/components/feature/global-search/GlobalSearch.tsx
raven-app/src/components/feature/global-search/MessageSearch.tsx
raven-app/src/components/feature/global-search/styles.css
raven-app/src/components/feature/markdown-viewer/MarkdownRenderer.tsx
raven-app/src/components/feature/message-action-palette/ActionsPalette.tsx
raven-app/src/components/feature/message-details/EditMessageModal.tsx
raven-app/src/types/Messaging/Message.ts
raven-app/src/types/Search/FileSearch.ts
raven-app/src/utils/operations.ts
raven/api/preview_links.py
raven/api/search.py
raven/raven_messaging/doctype/raven_message/raven_message.json
raven/raven_messaging/doctype/raven_message/raven_message.py
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.js
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.json
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.py
raven/raven_messaging/doctype/raven_message_reaction/test_raven_message_reaction.py

172 users should be able to react to messages

---

raven-app/src/components/feature/channels/ChannelList.tsx
raven-app/src/components/feature/channels/DirectMessageList.tsx
raven-app/src/components/layout/Sidebar/Sidebar.tsx
raven-app/src/components/layout/Sidebar/SidebarComp.tsx

168 fix sidebar footer

---

README.md

fix: installation guide

---

raven-app/src/components/feature/channels/ViewChannelDetailsModal.tsx
raven-app/src/components/feature/settings/ArchiveChannel.tsx
raven-app/src/components/feature/settings/ChangeChannelType.tsx
raven-app/src/components/feature/settings/ChannelSettings.tsx
raven-app/src/components/feature/settings/DeleteChannel.tsx
raven/raven_channel_management/doctype/raven_channel/raven_channel.json
raven/raven_channel_management/doctype/raven_channel/raven_channel.py
raven/www/raven_app.html

192 channel creator can deletearchive channel and all its messages

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/styles.css
raven-app/src/components/feature/markdown-viewer/MarkdownRenderer.tsx

added copy button in code blocks

---

raven-app/src/components/feature/command-palette/CommandPaletteActions.tsx

fix: styling in people search

---

raven-app/src/components/feature/chat/ChatMessage/ChatMessageBox.tsx
raven-app/src/components/feature/global-search/MessageSearch.tsx

fix: view channel link visible on hover

---

raven-app/src/components/feature/chat/ChatHistory.tsx
raven-app/src/components/feature/chat/ChatInput.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/chat/ChatMessage/ChatMessageBox.tsx
raven-app/src/components/feature/chat/MessageReply/PreviousMessageBox.tsx
raven-app/src/components/feature/markdown-viewer/MarkdownRenderer.tsx
raven-app/src/components/feature/message-action-palette/ActionsPalette.tsx
raven-app/src/types/Messaging/Message.ts
raven/raven_messaging/doctype/raven_message/raven_message.json
raven/raven_messaging/doctype/raven_message/raven_message.py

171 users should be able to reply to messages

---

raven-app/src/App.tsx
raven-app/src/utils/auth/UserProvider.tsx
raven-app/src/utils/channel/ChannelProvider.tsx
raven-app/src/utils/channel/ChannelRedirect.tsx
raven/raven_messaging/doctype/raven_message/raven_message.py

feat: storing last channel in local storage
fix: removed get_last_channel API

fix: removed get_last_channel API

---

raven-app/src/components/feature/channel-details/EditChannelDetails/AddOrEditChannelDescriptionModal.tsx
raven-app/src/components/feature/channel-details/EditChannelDetails/ChannelRenameModal.tsx
raven-app/src/components/feature/channel-details/EditChannelDetails/LeaveChannelModal.tsx
raven-app/src/components/feature/channel-details/EditChannelDetails/RemoveChannelMemberModal.tsx
raven-app/src/components/feature/channels/AddChannelMemberModal.tsx
raven-app/src/components/feature/channels/CreateChannelModal.tsx
raven-app/src/components/feature/chat/ChatInput.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/files/FilesSharedInChannel.tsx
raven-app/src/components/feature/global-search/ChannelSearch.tsx
raven-app/src/components/feature/global-search/FileSearch.tsx
raven-app/src/components/feature/message-details/DeleteMessageModal.tsx
raven-app/src/components/feature/message-details/EditMessageModal.tsx
raven-app/src/components/feature/saved-messages/SavedMessages.tsx
raven-app/src/components/feature/settings/ArchiveChannel.tsx
raven-app/src/components/feature/settings/ChangeChannelType.tsx
raven-app/src/components/feature/settings/DeleteChannel.tsx
raven-app/src/components/feature/user-details/UserProfileDrawer.tsx
raven-app/src/components/layout/AlertBanner/AlertBanner.tsx
raven-app/src/components/layout/AlertBanner/ErrorBanner.tsx
raven-app/src/components/layout/AlertBanner/index.ts
raven-app/src/pages/auth/Login.tsx
raven-app/src/utils/channel/ChannelProvider.tsx
raven/raven_channel_management/doctype/raven_channel/raven_channel.py
raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py

1. Added an ErrorBanner component to show better error output
2. Check if the channel exists before fetching it's details
3. Check if the user ID exists before fetching further details

fix: check for channel existence and throw relevant error

---

mobile/src/components/features/channels/AddChannel.tsx
raven-app/src/components/feature/channels/CreateChannelModal.tsx
raven/raven_channel_management/doctype/raven_channel/raven_channel.py
raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.json
raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py

1. Removed default date for last timestamp
2. Removed API for create channel

fix: moved channel creation to standard API

---

mobile/src/components/features/direct-messages/PrivateMessages.tsx
raven-app/src/components/feature/channels/ChannelList.tsx
raven-app/src/components/feature/channels/CreateChannelModal.tsx
raven-app/src/components/feature/channels/DirectMessageList.tsx
raven-app/src/components/feature/chat/ChatInterface.tsx
raven-app/src/components/feature/command-palette/CommandPalette.tsx
raven-app/src/components/feature/command-palette/CommandPaletteActions.tsx
raven-app/src/components/feature/saved-messages/SavedMessages.tsx
raven-app/src/components/layout/Sidebar/SidebarBody.tsx
raven-app/src/hooks/useGetUser.ts
raven-app/src/hooks/useIsUserActive.ts
raven-app/src/pages/MainPage.tsx
raven-app/src/utils/channel/ChannelListProvider.tsx
raven-app/src/utils/channel/ChannelProvider.tsx
raven-app/src/utils/layout/channelIcon.ts
raven-app/src/utils/users/ActiveUsersProvider.tsx
raven-app/src/utils/users/UserListProvider.tsx
raven/api/raven_users.py
raven/raven_channel_management/doctype/raven_channel/raven_channel.py

1. Removed unused API calls
2. Moved user list and channel data to global context
3. Moved user active state to global context
Closes #363 and #364

fix: more like chore

---

mobile/src/App.tsx
raven-app/src/App.tsx

fix: set socket port undefined on Prod

---

raven-app/src/components/feature/chat-header/ViewOrAddMembersButton.tsx
raven-app/src/components/layout/EmptyState/EmptyState.tsx
raven/api/raven_users.py

fix: hide buttons from non-members

---

mobile/src/types/RavenMessaging/RavenMessageReaction.ts
raven-app/src/components/feature/chat/chat-message/MessageReactions.tsx
raven-app/src/components/feature/message-action-palette/ActionsPalette.tsx
raven-app/src/types/RavenMessaging/RavenMessageReaction.ts
raven/api/reactions.py
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.json
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.py

https://github.com/The-Commit-Company/Raven/issues/439#issue-1884675043

fix: performance and calculation issues in reactions

---

mobile/dev-dist/registerSW.js
mobile/dev-dist/sw.js
mobile/dev-dist/workbox-b7fccfec.js
mobile/index.html
mobile/package.json
mobile/src/App.tsx
mobile/src/hooks/useIsUserActive.tsx
mobile/src/utils/auth/Routes.tsx
mobile/src/utils/auth/UserProvider.tsx
mobile/src/utils/users/ActiveUsersProvider.tsx
mobile/vite.config.ts
mobile/yarn.lock
raven-app/src/components/feature/markdown-viewer/MarkdownRenderer.tsx
raven-app/src/components/layout/AlertBanner/AlertBanner.tsx
raven-app/src/hooks/useActiveState.tsx
raven-app/src/hooks/useIsUserActive.ts
raven-app/src/utils/users/ActiveUsersProvider.tsx
raven/api/user_availability.py
raven/raven_messaging/doctype/raven_message/raven_message.py

fix: user activity status is accurately updated Closes #463
chore: setup Vite-PWA. Closes #464
feat: added Warning banner when no network. Closes #456

fix(mobile): user active status, network warning

---

mobile/src/components/common/UserAvatar.tsx
mobile/src/components/features/channels/AddChannel.tsx
mobile/src/components/features/channels/AddChannelMembers.tsx
mobile/src/components/features/chat-space/ChatInterface.tsx
mobile/src/components/features/chat-space/chat-header/ChannelHeader.tsx
mobile/src/pages/channels/ChannelSettings.tsx
mobile/src/utils/auth/Routes.tsx

feat: add channel members modal in channel settings

---

mobile/src/components/layout/loaders/ProfileLoader.tsx
mobile/src/pages/profile/Profile.tsx

fix: add skeleton loader in Profile page (Mobile)

---

mobile/src/components/features/chat-input/tiptap.styles.css
raven-app/src/components/feature/chat/ChatInput/tiptap.styles.css

fix: Add a scroll bar to the Chat Input in Web & Mobile App

---

api_docs/Chat/Get Channel Members.bru
api_docs/Preview Links/Get Preview Link.bru
api_docs/Raven Users/Get List.bru
api_docs/Reactions/React.bru
api_docs/User Availability/Get Active Users.bru
api_docs/User Availability/Refresh User Active State.bru
api_docs/bruno.json
api_docs/environments/Dev.bru
mobile/src/components/features/chat-space/ChatInterface.tsx
mobile/src/types/RavenChannelManagement/RavenChannel.ts
raven-app/src/components/feature/chat/chat-history/ChatBoxBody.tsx
raven-app/src/components/layout/Sidebar/SidebarBody.tsx
raven-app/src/types/RavenChannelManagement/RavenChannel.ts
raven-app/yarn.lock
raven/api/chat.py
raven/api/preview_links.py
raven/api/raven_users.py
raven/api/reactions.py
raven/hooks.py
raven/permissions.py
raven/raven_channel_management/doctype/raven_channel/raven_channel.json
raven/raven_channel_management/doctype/raven_channel/raven_channel.py
raven/raven_messaging/doctype/raven_message/raven_message.json
raven/raven_messaging/doctype/raven_message/raven_message.py
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.json
raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.py

All APIs moved to the /api folder and a Bruno collection created for docs. Validation checks added to all APIs - pending.

fix: api docs, permissions and security

---

raven/api/upload_file.py

Hopefully, this fixes the rotation issue🤞🏼

fix: upload JPEG images w/ EXIF transpose

---

raven-app/src/utils/operations.ts

fix: show users' `full_name` when 2/ 3 users have reacted & user is not `currentUser`

---

mobile/src/components/features/channels/ChannelList.tsx
mobile/src/components/features/direct-messages/DirectMessages.tsx
mobile/src/pages/channels/Channels.tsx
mobile/src/pages/direct-messages/DirectMessageList.tsx

485 rav 6 show unread message counts for channels and dms on the mobile app

---

raven-app/src/components/layout/AlertBanner/MobileAppRedirectBanner.tsx
raven-app/src/components/layout/AlertBanner/index.ts
raven-app/src/components/layout/AlertBanner/styles.css
raven-app/src/main.tsx
raven-app/src/pages/MainPage.tsx

When viewport width is less than ~700px, show banner suggesting to open mobile app (PWA)

feat: add support for mobile app discoverability

---

raven-app/public/frappe-push-notification.js
raven/__init__.py
raven/raven_messaging/doctype/raven_message/raven_message.py

Fixes the issues regarding two apps on same site
Also, update the `frappe` framework on FC

fix: update js and python client

---

raven-app/src/components/feature/raven-users/AddRavenUsersContent.tsx
raven-app/src/components/feature/raven-users/UsersTable.tsx

feat: show warning if role profile is added to user

---

raven-app/src/components/feature/chat/ChatStream/ChatHistory.tsx
raven/api/raven_message.py
types/Messaging/Message.ts

fix: re-render message block if modified

---

raven-app/src/components/feature/chat-header/ChannelHeader.tsx
raven-app/src/components/feature/chat-header/DMChannelHeader.tsx
raven-app/src/components/feature/files/FilesTable.tsx
raven-app/src/components/feature/files/ViewFilesButton.tsx
raven-app/src/components/feature/files/ViewFilesContent.tsx
raven-app/src/hooks/useFileURLCopy.ts
raven-app/src/utils/operations.ts
raven/api/raven_message.py
raven/api/upload_file.py

https://github.com/The-Commit-Company/Raven/assets/29656465/53ab5d16-42f4-4ed3-b9f5-ec85fcff6025

feat: allow users to view and search files shared in a channel easily

---

mobile/src/components/features/chat-space/MessageActions/EmojiAction.tsx
mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
mobile/src/components/features/chat-space/chat-view/components/MessageReactions.tsx

Added a mutate for the message stream when a user reacts to a message

fix(mobile): refresh messages when user reacts

---

mobile/src/components/features/chat-space/chat-view/components/MessageReactions.tsx

fix(ui): wrap reactions on mobile app

---

mobile/src/index.css

Solution:
- Changed background variable value in index.css

fix(mobile): change bg color for auth pages to match rest of the app

---

mobile/src/components/features/chat-space/useChatStream.ts
raven-app/src/components/feature/chat/ChatStream/useChatStream.ts

Added check on both mobile and web

fix: check if bot message when deciding message stream

---

raven-app/src/components/feature/channels/ChannelList.tsx
raven-app/src/components/feature/channels/CreateChannelModal.tsx
raven-app/src/components/feature/direct-messages/DirectMessageList.tsx
raven-app/src/components/layout/Sidebar/SidebarBody.tsx
raven-app/src/components/layout/Sidebar/SidebarComp.tsx
raven-app/src/components/layout/Sidebar/UnreadChannels.tsx

feat: show unread channels and DMs in a separate section

---

mobile/src/components/auth/ForgotPasswordButton.tsx
mobile/src/components/auth/SocialProviders.tsx
mobile/src/components/layout/AuthContainer.tsx
mobile/src/pages/auth/ForgotPassword.tsx
mobile/src/pages/auth/Login.tsx
mobile/src/pages/auth/LoginWithEmail.tsx
mobile/src/pages/auth/SignUp.tsx
mobile/src/types/Auth/Login.ts
raven-app/src/App.tsx
raven-app/src/pages/auth/ForgotPassword.tsx
raven-app/src/pages/auth/Login.tsx
raven-app/src/pages/auth/LoginWithEmail.tsx
raven-app/src/types/Auth/Login.ts

This PR introduces a new forgot password feature, allowing users to reset their password directly from the login page of Raven. The key additions implemented are:
1. Added a "Forgot Password" link on the login page that navigates the user to the forgot password page.
2. Created a form on the forgot password page where users can enter their email and request a password reset email.
3. Added a "Back to Login" button to allow users to navigate back to the login page.
4. Displayed success and error messages to the user based on the status of the password reset email. (This can be changed later, upon fixing Error Banner.)
5. Redirected the user to the reset password page when they click the link in the password reset email.
6. Showed Frappe's reset password page where users can enter and …

feat: allow users to request a password change via a forgot password page

---

raven-app/package.json
raven-app/src/components/common/GIFPicker/GIFFeaturedResults.tsx
raven-app/src/components/common/GIFPicker/GIFSearchResults.tsx
raven-app/yarn.lock

Add pagination (Cursor Based in Serial mode) in GIF Picker using `useSWRInfinite` hook.

feat: add pagination in gif picker

---

raven-app/src/components/feature/chat/ChatInput/TextFormattingMenu.tsx
raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx

- Added Keyboard shortcut for toggling CodeBlock. Press Cmd + Shift + E to toggle the code block.

fix: added keyboard shortcut for code block

---

raven/raven_messaging/doctype/raven_message/raven_message.py

**Problem**:
The `showNotification` API expects the timestamp to be provided in **milliseconds** since the epoch
Ref: https://web.dev/articles/push-notifications-display-a-notification#timestamp
But Raven was sending this in **seconds**.
`get_timestamp` function from the framework **returns time in seconds** since epoch and it also doesn't consider time for the datetime object - uses `getdate` internally so not very reliable
After I calculated & passed the milliseconds since the epoch, android showed (in 5 hrs). Epoch being timezone unaware, the OS seemed to be converting the timestamp to the user timezone _somehow_ (guessing because IST is UTC + 5:30)
So tried converting system datetime to UTC and this seems to be reflecting correctly. 
These changes don't seem to affect iOS. Looks like …

fix: push notification timestamp

---

raven-app/src/App.tsx
raven-app/src/components/feature/chat/ChatMessage/MessageActions/RetractVote.tsx
raven-app/src/components/feature/chat/ChatMessage/Renderers/PollMessage.tsx
raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Link.tsx
raven-app/src/hooks/useCurrentRavenUser.ts
raven-app/src/hooks/useUnreadMessageCount.ts
raven-app/src/pages/auth/Login.tsx
raven-app/src/utils/channel/ChannelListProvider.tsx
raven-app/src/utils/channel/ChannelMembersProvider.tsx

Channels and members need to be refetched on refresh/load

fix: refetch channels and members on load

---

raven-app/src/components/feature/chat/ChatMessage/MessageItem.tsx
raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Link.tsx
raven/api/preview_links.py

fix: show twitter link previews

---

mobile/src/utils/channel/ChannelListProvider.tsx
raven-app/src/components/feature/direct-messages/DirectMessageList.tsx
raven-app/src/components/layout/Sidebar/SidebarComp.tsx
raven-app/src/utils/channel/ChannelListProvider.tsx
raven/api/raven_channel.py

Removed extra users and fixed styling in the sidebar

perf: removed query for extra users

---

frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/tiptap-renderer.styles.css

fix(ui): color links in messages

---

frontend/src/components/feature/polls/CreatePoll.tsx

chore: fix placeholders in create poll modal

---

frontend/src/components/common/LinkField/LinkField.tsx
frontend/src/components/feature/chat-header/ChannelHeaderMenu.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Link.tsx
frontend/src/components/feature/integrations/meetings/CreateMeetingDialog.tsx
frontend/src/components/feature/integrations/meetings/CreateMeetingForm.tsx
raven/api/events.py
raven/api/raven_message.py

To use this feature, enable Google Settings and Google Calendar for your users.
https://github.com/user-attachments/assets/63f20cbc-ab53-4f04-9766-aa14b199de3c

feat: start Google Meet via events from a channel

---

frontend/src/components/feature/channel-details/leave-channel/LeaveChannelButton.tsx
frontend/src/components/feature/channel-details/leave-channel/LeaveChannelModal.tsx
frontend/src/components/feature/channel-settings/archive-channel/ArchiveChannelButton.tsx
frontend/src/components/feature/channel-settings/archive-channel/ArchiveChannelModal.tsx
frontend/src/components/feature/channel-settings/change-channel-type/ChangeChannelTypeButton.tsx
frontend/src/components/feature/channel-settings/delete-channel/DeleteChannelButton.tsx
frontend/src/components/feature/channel-settings/delete-channel/DeleteChannelModal.tsx

Channel actions on mobile were not working because of modals hiding underneath the drawer.

fix: channel action drawers on mobile

---

raven/raven_integrations/controllers/employee.py

This didn't let me create a new Employee.

fix: return type can be None

---

frontend/src/App.tsx
frontend/src/components/feature/settings/common/DeleteAlert.tsx
frontend/src/components/feature/userSettings/Users/AddUserDialog.tsx
frontend/src/pages/settings/AI/BotList.tsx
frontend/src/pages/settings/Users/UserList.tsx
raven/api/raven_users.py

If the user is already in the system, the "Raven User" role is added. If not, an invite is sent to them.

feat: allow inviting users from Raven

---

frontend/src/components/common/UserLeaveBadge.tsx
frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Mention.tsx

Also added the "On Leave" badge in user hover cards

feat: clicking user mentions takes user to DM channel

---

frontend/src/App.tsx
frontend/src/pages/ErrorPage.tsx

feat: added error page for crashes

---

frontend/src/components/feature/chat/ChatInput/TextFormattingMenu.tsx
frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
frontend/src/components/feature/chat/ChatInput/useSendMessage.ts
frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TimestampRenderer.tsx

Added a separate button to embed timestamps. Conversations were getting out of hand lol.

fix: embed time action

---

frontend/index.html
frontend/src/components/layout/AuthContainer.tsx
frontend/src/utils/auth/ProtectedRoute.tsx
frontend/src/utils/users/UserListProvider.tsx

Standard APIs that are needed to run Raven are pre-fetched now. Will add caching to these later.

perf: prefetch resources

---

frontend/src/App.tsx
frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx

fix: width of message item content

fix: pass sitename to SocketIO. Do not pass if v14

---

apps/mobile/app/[site_id]/(tabs)/profile/custom_status.tsx
apps/mobile/app/[site_id]/(tabs)/profile/fullname.tsx
apps/mobile/app/[site_id]/(tabs)/profile/index.tsx
packages/lib/hooks/useCurrentRavenUser.ts

https://github.com/user-attachments/assets/5f7a83f1-7fbf-47bd-8890-a7d7aef24523
**We need to select a suitable emoji picker for the custom status field.**

feat(mobile): profile actions - edit name and status

---

apps/mobile/components/common/GIFPicker/GIFFeaturedResults.tsx
apps/mobile/components/common/GIFPicker/GIFPicker.tsx
apps/mobile/components/common/GIFPicker/GIFPickerKeys.ts
apps/mobile/components/common/GIFPicker/GIFSearchResults.tsx

https://github.com/user-attachments/assets/6bf89f09-88b3-4f6b-bd16-729943293c9c

feat(mobile): GIF picker drawer

---

frontend/src/components/common/UserAvatar.tsx
frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx

Some SVGs has sizes set to "rem" which is invalid.

fix: remove invalid SVG sizes

---

frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/LinkPreview.tsx

When a YouTube link is sent on Raven, a YouTube embed is available for viewing the video instead of a link preview.
Did not use Tiptap's extension for this since that would have embedded the iframe within the HTML message content - and that would be an issue on the native mobile app. Also, this solution will work even if the YouTube link is sent via an automated bot (@NagariaHussain might want to do this for community notifications)

feat(web): YouTube videos appear as embeds in link previews

---

raven/raven_bot/doctype/raven_bot/raven_bot.py

If we get an error for `model_not_found`, it's usually because the model is not available to the user:
1. Most likely the user has not added any funds to their OpenAI account. - this is what's happening now since gpt-4o is available to everyone. 
2. When we eventually allow users to select a specific model, it could be that some models are not available for certain accounts/regions. 
Hence, changed the error message to guide the user:

fix: throw relevant error for OpenAI model not found

---

frontend/src/components/feature/chat/ChatInput/FileInput/useFileUpload.ts
frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
frontend/src/components/feature/userSettings/UploadImage/UploadImageModal.tsx
raven/api/upload_file.py

Other changes:
Workspace logos and user avatars will always be optimised

feat(web): allow users to choose if they wish to compress images when uploading

---

raven/raven_integrations/doctype/raven_document_notification/raven_document_notification.py
raven/utils.py

fix(compat): support for Frappe v14 - replace cache calls

---

apps/mobile/components/features/chat-stream/DateSeparator.tsx
apps/mobile/components/features/chat-stream/MessageItem.tsx
apps/mobile/components/features/chat-stream/MessageItemElements/MessageHeader.tsx
apps/mobile/components/features/chat-stream/SystemMessageBlock.tsx
apps/mobile/hooks/useChatStream.ts
apps/mobile/hooks/useFormatDate.ts
apps/mobile/package.json
apps/mobile/types/SiteInformation.ts
packages/types/common/Message.ts
raven/api/raven_mobile.py
yarn.lock

feat(mobile): formatted dates on chat stream

---

apps/mobile/components/features/channels/ChannelList/ChannelListRow.tsx
apps/mobile/components/features/channels/ChannelList/ChannelListUI.tsx
apps/mobile/package.json
yarn.lock

**Leave channel** 
https://github.com/user-attachments/assets/13738d5a-5fe0-41d5-97d7-9e4c6a90e66b

feat(mobile): added zeego context menu

---

frontend/src/components/feature/document-notifications/DocumentNotificationForm.tsx
raven/raven_integrations/doctype/raven_document_notification/raven_document_notification.py

fix(integrations): check for docfield in Document Notification

---

apps/mobile/app/[site_id]/(tabs)/home/browse-channels.tsx
apps/mobile/app/[site_id]/(tabs)/home/quick-search.tsx
apps/mobile/app/[site_id]/(tabs)/home/saved-messages.tsx
apps/mobile/components/features/chat-stream/MessageItem.tsx
apps/mobile/components/features/chat-stream/MessageItemElements/MessageAvatar.tsx
apps/mobile/components/features/saved-messages/SavedMessageItem.tsx
apps/mobile/components/features/saved-messages/ViewSavedMessagesButton.tsx
apps/mobile/global.css
apps/mobile/hooks/useChatStream.ts
apps/mobile/tailwind.config.js
packages/lib/hooks/useCurrentChannelData.ts
packages/lib/hooks/useGetUserRecords.ts
packages/lib/utils/dateConversions.ts

https://github.com/user-attachments/assets/53bb0dc3-02f3-4faf-b60c-bb3d1320a069
Scroll to message functionality is pending

feat(mobile): saved messages page

---

apps/mobile/components/features/chat/ChatMessage/Renderers/LinkPreview.tsx
apps/mobile/hooks/useLinkPreview.ts

feat(mobile): Link Preview

---

frontend/src/components/feature/workspaces/WorkspaceMemberManagement.tsx

fix(web): highlight selected member row in dark mode

---

raven/raven_integrations/doctype/raven_document_notification/raven_document_notification.py

fix: validate condition on document notification

---

frontend/src/components/feature/chat-header/DMChannelHeader.tsx

fix(PWA): do not deselect last used workspace on going back from DM

---

frontend/package.json
yarn.lock

Updated RadixUI Themes to v3.2.0 - this includes the fix for the flicker issue on dialogs. Might also be related to #1288 but will test on Firefox.

fix: flicker when dialog closed

---

frontend/src/pages/settings/Workspaces/ViewWorkspace.tsx

- Disabled set to loading should not be a form state.

fix: remove disabled state in useForm

---

frontend/src/components/feature/chat/ChatInput/Tiptap.tsx

fix: allow newline on mobile PWA

---

frontend/src/components/feature/CommandMenu/ChannelItem.tsx
frontend/src/components/feature/CommandMenu/ChannelList.tsx
frontend/src/components/feature/channel-settings/delete-channel/DeleteChannelButton.tsx
frontend/src/components/layout/Sidebar/useGetChannelUnreadCounts.ts
frontend/src/utils/channel/ChannelListProvider.tsx
raven/api/raven_channel.py
raven/raven_channel_management/doctype/raven_channel/raven_channel.py

Public channels can still be found using CMD+K or Search
Closes #1247 and #1302

fix: only show public channels where the user is a member on the sidebar

---

apps/mobile/app/[site_id]/chat/[id]/index.tsx
apps/mobile/components/features/channel-settings/ChannelInfoModal.tsx
apps/mobile/components/features/channel-settings/PushNotifications.tsx
apps/mobile/components/features/chat/ChatHeader/ChannelHeader.tsx
apps/mobile/components/features/chat/ChatHeader/DMChannelHeader.tsx
apps/mobile/components/layout/UserAvatar.tsx

feat(mobile): added headers for both DMs and Channels

---

apps/mobile/app/[site_id]/(tabs)/home/quick-search.tsx
apps/mobile/components/features/chat-stream/ChatStream.tsx
apps/mobile/components/features/chat-stream/FirstMessageBlock.tsx

feat(mobile): added first message block for chat stream

---

apps/mobile/app/[site_id]/chat/[id]/channel-settings.tsx
apps/mobile/app/[site_id]/chat/[id]/file-viewer.tsx
apps/mobile/app/[site_id]/chat/[id]/index.tsx
apps/mobile/components/common/HeaderBackButton.tsx
apps/mobile/components/common/ImagePickerButton.tsx
apps/mobile/components/features/chat/ChatInput/SendItem.tsx
apps/mobile/components/features/image/ImageViewer.tsx

https://github.com/user-attachments/assets/69eb1d78-870a-4de1-8d2f-819d475adccc

fix: Image View layout

---

frontend/src/components/feature/chat/ChatMessage/MessageActions/ForwardMessage.tsx
frontend/src/components/feature/message-actions/MessageActionModal.tsx
frontend/src/components/feature/selectDropdowns/MultipleUserCombobox.tsx

fix(ui): change colors on dropdown items

---

frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
frontend/src/hooks/useStickyState.ts

Moved from session storage to local storage

feat: store draft messages in local storage

---

frontend/src/components/feature/chat/ChatInput/FileInput/useFileUpload.ts
frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
frontend/src/components/feature/chat/ChatMessage/ActionModals/EditMessageModal.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/AttachFileToDocument.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/DeleteMessage.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/EditMessage.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/ForwardMessage.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/MessageReactionAnalytics.tsx
frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
frontend/src/components/feature/chat/ChatStream/ChatStream.tsx
frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx

Also added a handler to focus the editor back after closing any modal (edit, delete etc)

feat: up arrow to edit last sent text message

---

frontend/src/components/feature/chat/ChatMessage/ActionModals/ForwardMessageModal.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/MessageActions.tsx
frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/CreateThreadButton.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/ImageMessage.tsx
frontend/src/utils/operations.ts
raven/api/raven_channel.py

This would only work on HTTPS sites + no sure if this works on Firefox.

feat: copy image to clipboard

---

raven/api/reactions.py

Will work on any new reactions

fix: fetch reactions ordered by creation when setting in JSON

---

frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx

_HR just called. Sending flying kisses to your coworkers is not a joke Jim!_

revert: stupid emoji suggestions

---

frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx
frontend/src/pages/settings/Preferences.tsx
frontend/src/utils/preferences.ts

feat: allow users to configure quick reaction emojis

---

frontend/src/components/feature/threads/Threads.tsx
frontend/src/components/feature/userSettings/UserProfile/UserProfile.tsx

Looks like the issue was when users uploaded a file, then also hit save.

fix: do not update user image on save

---

frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx
frontend/src/components/feature/threads/ThreadPreviewBox.tsx
frontend/src/components/layout/Sidebar/MentionsButton.tsx
frontend/src/components/layout/Sidebar/SidebarHeader.tsx
frontend/src/types/Raven/RavenUser.ts
raven/api/mentions.py
raven/api/threads.py
raven/raven/doctype/raven_user/raven_user.json
raven/raven/doctype/raven_user/raven_user.py
raven/raven_messaging/doctype/raven_message/raven_message.py

feat: user mention notifications

---

frontend/src/components/common/ImageViewer.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/ImageMessage.tsx

https://github.com/user-attachments/assets/bd907c67-aabd-4992-bcf7-c03ddabbcf86
Closes #1428

feat: zoom and pan images on PWA

---

frontend/src/components/feature/chat/ChatInput/FileInput/useFileUpload.ts
frontend/src/components/feature/chat/ChatInput/useSendMessage.ts
frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx
raven/api/upload_file.py

fix: send image as reply to message

fix: send images without content

---

frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Mention.tsx

feat: start DM from user hover card

---

frontend/src/pages/settings/AI/OpenAISettings.tsx
raven/api/ai_features.py

feat: show OpenAI Python SDK version installed on the bench

---

frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
frontend/src/components/feature/chat/ChatInput/tiptap.styles.css
frontend/src/components/feature/chat/ChatMessage/ReplyMessageBox/ReplyMessageBox.tsx
frontend/src/components/feature/threads/ThreadDrawer/ThreadFirstMessage.tsx
frontend/src/components/layout/Sidebar/MentionsButton.tsx
frontend/src/utils/operations.ts
raven/api/mentions.py

fix(ui): miscellaneous UI fixes on web

---

frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx

fix: line height in message text

---

apps/mobile/app.json
apps/mobile/app/[site_id]/_layout.tsx
apps/mobile/app/[site_id]/chat/[id]/index.tsx
apps/mobile/components/features/channels/ChannelList/ChannelListRow.tsx
apps/mobile/components/features/chat-stream/ChatStream.tsx
apps/mobile/components/features/chat-stream/FirstMessageBlock.tsx
apps/mobile/components/features/chat-stream/MessageItemElements/MessageTextRenderer.tsx
apps/mobile/components/features/chat/ChatInput/ChatInput.tsx
apps/mobile/components/features/chat/ChatInput/Tiptap/TextFormattingMenu.tsx
apps/mobile/components/features/chat/ChatInput/Tiptap/Tiptap.tsx
apps/mobile/components/features/chat/ChatInput/Tiptap/tiptap.module.css
apps/mobile/hooks/useChatStream.ts
apps/mobile/hooks/useColorScheme.ts
apps/mobile/hooks/useGetCurrentWorkspace.ts
apps/mobile/lib/Providers.tsx

1. Keyboard opening behaviour of chat stream/input improved.
2. Theme and workspace are now stored in AsyncStorage

fix(mobile): improvements on chat stream

---

frontend/src/components/feature/CommandMenu/CommandMenu.tsx
frontend/src/components/feature/CommandMenu/commandMenu.styles.css
frontend/src/index.css
frontend/src/utils/layout/dialog.ts

fix(web): better dialog frost effect

---

apps/mobile/app/+not-found.tsx
apps/mobile/app/[site_id]/(tabs)/profile/custom-status.tsx
apps/mobile/app/[site_id]/(tabs)/profile/fullname.tsx
apps/mobile/app/[site_id]/(tabs)/profile/index.tsx
apps/mobile/app/[site_id]/(tabs)/profile/preferences.tsx
apps/mobile/components/features/chat-stream/MessageItem.tsx
apps/mobile/components/features/chat/ChatMessage/MessageActions/QuickReactions.tsx
apps/mobile/components/features/profile/profile-settings/Preferences.tsx
apps/mobile/hooks/useChatStream.ts
apps/mobile/lib/preferences.ts
packages/lib/hooks/useReactToMessage.ts
packages/types/common/ChatStream.ts

https://github.com/user-attachments/assets/c490bb51-6766-4c06-a095-b656f216afbf

feat(mobile): react to message

---

apps/mobile/app/[site_id]/chat/[id]/channel-settings.tsx
apps/mobile/components/features/channel-settings/ArchiveChannel.tsx
apps/mobile/components/features/channel-settings/ChangeChannelType.tsx
apps/mobile/components/features/channel-settings/DeleteChannelModal.tsx
apps/mobile/components/features/channel-settings/LeaveChannel.tsx
apps/mobile/components/features/channel-settings/PushNotifications.tsx
apps/mobile/components/features/channels/DMList/DMRow.tsx

feat(mobile): show channel settings based on user permissions

---

apps/mobile/app/[site_id]/(tabs)/home/browse-channels.tsx
apps/mobile/app/[site_id]/(tabs)/home/create-dm.tsx
apps/mobile/app/[site_id]/(tabs)/home/quick-search.tsx

https://github.com/user-attachments/assets/4d427b2e-edaa-4318-b07e-388011faa1aa

feat(mobile): Quick search

---

apps/mobile/components/features/chat/ChatInput/ChatInput.tsx
apps/mobile/components/features/chat/ChatMessage/Renderers/DocTypeLinkRenderer.tsx

https://github.com/user-attachments/assets/84a9ac75-a3f2-40d5-90dd-250d9f8c1271

feat(mobile): document link previews

---

apps/mobile/app/[site_id]/_layout.tsx
apps/mobile/app/_layout.tsx
apps/mobile/components/features/auth/AddSite.tsx
apps/mobile/components/features/chat-stream/ChatStream.tsx
apps/mobile/components/features/chat/ChatLayout.tsx

If the user is "near" the bottom of the screen, and opens the keyboard, the chat stream scrolls to end automatically - hence solving the issue with messages being "hidden" behind the keyboard.
https://github.com/user-attachments/assets/a48cbc7a-2f3d-4577-9ed5-10af73681f79

fix(mobile): chat stream scrolls up when keyboard opens

---

apps/mobile/app/[site_id]/(tabs)/profile/index.tsx
apps/mobile/app/[site_id]/_layout.tsx
apps/mobile/components/features/auth/SiteSwitcher.tsx
apps/mobile/components/features/auth/SitesList.tsx
apps/mobile/components/features/profile/profile-settings/SwitchSitesSetting.tsx
apps/mobile/components/features/workspaces/WorkspaceSwitcher.tsx
apps/mobile/hooks/useLogout.ts
apps/mobile/hooks/useSiteSwitcher.ts
packages/lib/utils/operations.ts

https://github.com/user-attachments/assets/e1dd3f39-e366-4679-a0a3-93dfabbc8445

feat(mobile): switch sites without logging out

---

apps/mobile/components/features/channel-settings/ArchiveChannel.tsx
apps/mobile/components/features/chat/ChatFooter/ArchivedChannelBox.tsx
apps/mobile/components/features/chat/ChatFooter/JoinChannelBox.tsx
apps/mobile/components/features/chat/ChatLayout.tsx
apps/mobile/hooks/useShouldJoinChannel.ts

feat(mobile): do not show chat input on channels where the user is not a member

---

apps/mobile/app/landing.tsx
apps/mobile/assets/icons/InfoIcon.svg
apps/mobile/components/features/auth/AddSite.tsx
apps/mobile/components/features/auth/HowToSetupMobile.tsx
apps/mobile/components/layout/FullPageLoader.tsx
apps/mobile/hooks/useSiteSwitcher.ts

feat(mobile): added instructions on setting up site for mobile

---

apps/mobile/components/features/chat/ChatMessage/MessageActions/SaveMessage.tsx
apps/mobile/components/features/saved-messages/SavedMessageItem.tsx
apps/mobile/components/nativewindui/AdaptiveSearchHeader/AdaptiveSearchHeader.tsx
apps/mobile/hooks/useSaveMessage.ts

feat: Unsave from list

---

frontend/src/components/feature/pinned-messages/PinnedMessageModalContent.tsx

Still need to improve the scroll behaviour when going to the pinned message

feat(web): navigate to pinned message

---

apps/mobile/app/[site_id]/(tabs)/home/quick-search.tsx
apps/mobile/components/common/SearchInput/SearchInput.tsx

fix(mobile): autofocus the search bar on quick search dialog

---

apps/mobile/components/common/Badge/UnreadCountBadge.tsx
apps/mobile/components/features/channels/DMList/DMRow.tsx
apps/mobile/components/features/channels/UnreadChannelList/ChannelItemElement.tsx
apps/mobile/components/features/channels/UnreadChannelList/DirectMessageItemElement.tsx
apps/mobile/components/features/channels/UnreadChannelList/UnreadChannelsList.tsx
apps/mobile/components/features/threads/ParticipatingThreads.tsx
apps/mobile/components/features/threads/ThreadPreviewBox.tsx
apps/mobile/components/features/threads/ThreadTabs.tsx

<Table>
<Tr>
<Td><img src='https://github.com/user-attachments/assets/13a2d9ea-0b2a-46be-9157-f375d918aa97'  /></Td>
<Td><img src='https://github.com/user-attachments/assets/96dda44a-eec0-4002-93d2-76390b7f7ade'  /></Td>
</Tr>
<Tr>
<Td><img src='https://github.com/user-attachments/assets/5784c1cd-24e8-49a6-8673-eac1c9eef22d'  /></Td>
<Td><img src='https://github.com/user-attachments/assets/264415ea-42be-45ff-95bd-2362bb3ef790'  /></Td>
</Tr>
<Tr>
<Td><img src='https://github.com/user-attachments/assets/562a223c-bdf8-4151-ba3d-af71508a85ff'  /></Td>
<Td><img src='https://github.com/user-attachments/assets/4e982d20-de50-4ac3-adf5-257525f9771b'  /></Td>
</Tr>
</Table>

feat(mobile): added common component for unread counts badge

---

apps/mobile/components/features/chat/ChatInput/TiptapEditor/TiptapEditor.tsx
apps/mobile/components/features/chat/ChatInput/TiptapEditor/tiptap.css
apps/mobile/components/features/chat/ChatMessage/MessageActions/EditMessageAction.tsx
apps/mobile/components/features/chat/ChatMessage/MessageActions/EditMessageSheet.tsx
apps/mobile/package.json
yarn.lock

fix(mobile): editor text color in dark mode

---

apps/mobile/components/features/chat/ChatInput/ChatInput.tsx
apps/mobile/components/features/chat/ChatMessage/Renderers/PollMessage.tsx
apps/mobile/package.json
frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
frontend/src/components/feature/chat/ChatMessage/Renderers/PollMessage.tsx
yarn.lock

fix(ui): minor UI fixes on web and mobile apps

---

frontend/src/components/feature/workspaces/WorkspaceActionMenu.tsx
frontend/src/pages/settings/Workspaces/ViewWorkspace.tsx

feat: rename and delete workspaces

---

raven/ai/openai_client.py
raven/raven/doctype/raven_settings/raven_settings.py
raven/raven_bot/doctype/raven_bot/raven_bot.py

- Strip trailing spaces from OpenAI Organization ID and Project ID in Raven Settings.
- Strip OpenAI API Key at runtime before connecting.
- Handle API connection errors with user-friendly messages.
Fixes issues where extra spaces in credentials caused OpenAI connection failures during Raven Bot creation and updates.
- Saved Raven Settings with extra spaces → Success
- Created/Updated Raven Bot → Success

fix: sanitize OpenAI fields and improve connection error handling

---

frontend/src/components/feature/settings/ai/bots/AIFeaturesBotForm.tsx
frontend/src/types/RavenBot/RavenBot.ts
raven/ai/openai_client.py
raven/api/ai_features.py
raven/raven_bot/doctype/raven_bot/raven_bot.json
raven/raven_bot/doctype/raven_bot/raven_bot.py

feat(ai): allow model selection when creating agents with reasoning effort for o-series models

---

apps/mobile/components/common/Buttons/ImagePickerButton.tsx
apps/mobile/package.json
yarn.lock

fix(mobile): convert HEIC to JPG on mobile app

---

frontend/src/components/feature/settings/help/SupportRequest.tsx

fix: add versions to help tickets

---

raven/raven/doctype/raven_push_token/raven_push_token.py

fix: invalidate push token cache

---

frontend/src/components/feature/settings/ai/functions/FunctionConstants.ts
frontend/src/components/feature/settings/ai/functions/FunctionForm.tsx
frontend/src/types/RavenAI/RavenAIFunction.ts
raven/ai/functions.py
raven/ai/handler.py
raven/raven_ai/doctype/raven_ai_function/raven_ai_function.json
raven/raven_ai/doctype/raven_ai_function/raven_ai_function.py

Allow AI functions to submit and cancel documents in the system

feat(ai): add support for submitting and cancelling documents

---

frontend/public/sw.js
frontend/src/utils/pushNotifications.ts
raven/notification.py
raven/raven_messaging/doctype/raven_message/raven_message.py

* chore: log background message payload
* fix: web push notifications
* fix: check if image exists
* fix: web push notification payload
* chore: log background message
* fix: foreground notifications on web

fix: web push notifications (#1737)

---

frontend/src/components/feature/settings/scheduler-events/SchedulerEventsForm.tsx
frontend/src/pages/settings/ServerScripts/SchedulerEvents/CreateSchedulerEvent.tsx

fix: set default value for day in SchedulerEventsForm
