The-Commit-Company/raven

- raven-app/src/components/feature/channel-details/ChannelDetails.tsx
- raven-app/src/components/feature/channel-details/EditChannelDetails/ChannelRenameModal.tsx
- raven-app/src/components/feature/channels/ChannelList.tsx
- raven-app/src/components/feature/channels/CreateChannelModal.tsx
- raven-app/src/components/feature/channels/ViewChannelDetailsModal.tsx
- raven-app/src/components/feature/chat/ChatInterface.tsx
- raven-app/src/components/feature/view-or-add-members/ViewOrAddMembersButton.tsx
- changed create channel modal to handle open channel creation
- added open channel in sidebar
- updated chat header to handle open channels
- updated view channel details modal for open channel
- fix: channel rename modal, channel length - 50, no special characters, cannot be empty
- removed add members button for open channels
this closes issue #57
> 58 open channels cannot be created from raven dashboard

- raven-app/src/components/feature/chat/ChatHistory.tsx
- raven-app/src/components/feature/chat/ChatInput.tsx
- raven-app/src/components/feature/chat/ChatInterface.tsx
- raven-app/src/components/feature/file-upload/FileListItem.tsx
- raven-app/src/types/Messaging/Message.ts
- raven-app/src/utils/operations.ts
- raven/raven_messaging/doctype/raven_message/raven_message.json
- raven/raven_messaging/doctype/raven_message/raven_message.py
users can upload files such as images (jpg, png, jpeg) and files (csv, xlsx, docx)
1. file messages are saved with file type (text, image or file)
2. file messages are saved in the DB, with upload progress and success, error states shown on the UI
3. file messages if of type image can be previewed/ downloaded and if of type file, can be downloaded from the UI
> 63 add support for file messages

- raven/raven_channel_management/doctype/raven_channel/raven_channel.json
- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
The API cannot be removed since the Raven Channel doctype does not store user IDs. I have added documentation and additional checks so that users cannot change the name of the channel
> feat: added validations

- mobile/src/App.tsx
Note: The back animation won't work on clicking '<' i.e., 'Back' button in iOS device.
> fix: back animation working on android device

- mobile/src/types/Raven/RavenSettings.ts
- raven-app/src/App.tsx
- raven-app/src/components/feature/raven-users/AddRavenUsersContent.tsx
- raven-app/src/components/layout/Sidebar/SidebarFooter.tsx
- raven-app/src/main.tsx
- raven-app/src/pages/AddRavenUsersPage.tsx
- raven-app/src/pages/MainPage.tsx
- raven-app/src/types/Raven/RavenSettings.ts
- raven-app/src/utils/roles.ts
- raven-app/src/utils/users/UserListProvider.tsx
- raven/api/raven_users.py
- raven/hooks.py
- raven/raven/doctype/raven_settings/raven_settings.js
- raven/raven/doctype/raven_settings/raven_settings.json
- raven/raven/doctype/raven_settings/raven_settings.py
- raven/raven/doctype/raven_settings/test_raven_settings.py
- raven/raven/doctype/raven_user/raven_user.json
- raven/raven/doctype/raven_user/raven_user.py
- raven/raven/module_onboarding/raven/raven.json
- raven/raven/onboarding_step/adding_users_to_raven/adding_users_to_raven.json
- raven/raven/onboarding_step/introduction_to_raven/introduction_to_raven.json
- raven/raven/onboarding_step/raven:_access_the_web_app/raven:_access_the_web_app.json
- raven/raven/onboarding_step/review_raven_settings/review_raven_settings.json
- raven/raven/workspace/raven/raven.json
1. Changed logic: Adding a Raven User role to any user will create a Raven User document
2. Deleting a Raven User also removes the role
3. Added setting to automatically add Raven User role to any System User
If the user is a system user:
If the user is not a system user and does not have a Raven User role:
Onboarding card added:
> feat: improve onboarding experience

- raven/raven/doctype/raven_user/raven_user.py
Currently with an LDAP login the frappe User stays Guest until DESK is loaded. Guest however does not have permission to create Raven User so an Error is given (and login is not possible)
> fix: permissions error for LDAP login

- raven/public/js/timeline_button.js
Also fix #622 #623 #620 
Note: tiptap works for bold italic but not works for table inside text, dont know how to fix that reference images below
> 620 multiple attachments shown when we send a message from the app

- mobile/src/components/features/chat-space/MessageActions/MessageActionModal.tsx
- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
- raven-app/src/components/feature/chat/ChatMessage/MessageItem.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- raven-app/src/components/feature/chat/ChatMessage/ReplyMessageBox/ReplyMessageBox.tsx
- raven/api/chat.py
- raven/api/raven_message.py
- raven/patches.txt
- raven/patches/v1_3/update_all_messages_to_include_replied_message_content.py
- raven/raven_messaging/doctype/raven_message/raven_message.json
- raven/raven_messaging/doctype/raven_message/raven_message.py
- types/Messaging/Message.ts
1. Added field for storing replied message block in a JSON field.
2. Patch added to migrate all existing messages to new structure
3. Reply blocks on web and mobile app now use the reply message's JSON instead of fetching the reply message block (perf 🚀). This alone cuts down multiple API calls when chats are loaded.
4. Reply blocks use the "content" field instead of the HTML field now. (Also perf 🚀). This means that the content would usually fit in a small section (lists would fit in one line for example).
5. Removed API to get reply message block content.
6. Removed truncated Tiptap editor on web app since it's not required anymore.
Also closes #608 
Towards #446 and #472
> feat: use copied replied message for showing reply block

- raven-app/src/components/common/EmojiPicker/EmojiPicker.tsx
Solution:
Toggle color change depending on the theme. Issue existed because By default, emoji-picker-element will automatically switch to dark mode based on prefers-color-scheme. Used colors from Tailwind's documentation. Can change if required.
Check Working images - 
Dark Mode - 
Light Mode -
> fix: emoji picker search text not visible in dark mode [#614]

- mobile/src/utils/channel/ChannelListProvider.tsx
- raven-app/src/utils/channel/ChannelListProvider.tsx
- raven/api/raven_channel.py
I think we should not fetch archived channels regardless. For now, by default, the API does not fetch archived channels.
> fix: do not show archived channels in Desk interface

- raven/public/scss/avatar.scss
> fix: set min-height and width for avatar in desk interface

- raven-app/src/pages/auth/Login.tsx
- raven-app/src/utils/auth/UserProvider.tsx
Fix:
If allow_login_using_user_name is set in System Settings for user, then we can use username while logging in.
Changes Made:
1) Removed email validation
2) Replaced ErrorBanner with ErrorCallout to show error message properly
3) Fixed arguments in login call inside UserProvider's handleLogin
> feat: Allow login via username

- raven-app/src/pages/ChatSpace.tsx
Fix:
Simply added channel Id in localstorage.
> fix: last channel opened not being maintained in local storage

- mobile/src/components/features/channels/channel-members/AddChannelMembers.tsx
- mobile/src/components/features/chat-input/Tiptap.tsx
- mobile/src/hooks/useGetUserRecords.ts
- mobile/src/types/Raven/RavenSettings.ts
- mobile/src/types/Raven/RavenUser.ts
- mobile/src/types/RavenMessaging/RavenMessage.ts
- mobile/src/utils/users/UserListProvider.tsx
- raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx
- raven-app/src/components/feature/command-palette/CommandPalette.tsx
- raven-app/src/components/feature/raven-users/AddRavenUsersContent.tsx
- raven-app/src/components/feature/select-member/AddMembersDropdown.tsx
- raven-app/src/hooks/useGetUserRecords.ts
- raven-app/src/pages/AddRavenUsersPage.tsx
- raven-app/src/types/Raven/RavenSettings.ts
- raven-app/src/types/Raven/RavenUser.ts
- raven-app/src/types/RavenMessaging/RavenMessage.ts
- raven-app/src/utils/channel/ChannelListProvider.tsx
- raven-app/src/utils/users/UserListProvider.tsx
- raven/api/raven_channel.py
- raven/api/raven_users.py
- raven/raven/doctype/raven_user/raven_user.json
- raven/raven_messaging/doctype/raven_message/raven_message.json
Also fixed the following:
1. List of Raven Users on the sidebar with which DM is not created was running a `get_list` query. If the user does not have access to the "User" doctype, this would fail. Changed this call to `get_all`. This will be changed later since we only want to query Raven User - but names would not be matching due to #658. 
2. When a Raven User is updated, we now update the User list as well as the channel list
3. User list fetched consists of both enabled and disabled users since there might be older messages for which we need to show names/avatars. But, while mentioning a user or adding them to a channel, we only enabled users. We would later also add a banner on DMs to inform users that a particular DM is disabled.
4. Website users can now be added as Raven Users
5. …
> fix: API path for creating a DM channel via search

- raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx
- raven-app/src/components/feature/chat/ChatInput/tiptap.styles.css
- raven-app/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
Fixes #682 
Also fixes an issue which did not scroll the message stream to the bottom if a message was sent by user
> fix: autofocus tiptap editor

- mobile/src/components/features/chat-space/MessageActions/CopyAction.tsx
- raven-app/src/components/feature/chat/ChatMessage/MessageActions/useMessageCopy.ts
Should fix the issue. Tested it with a few URLs. Might not work later when we have the ability to have text content different from links (embedded links)
> fix: do not escape underscores in url while copying

- mobile/src/components/ui/input-otp.tsx
Solution:
- add autofocus prop to OTPInput component. This is done with reference to [Shadcn's doc reference for input-otp](https://github.com/guilhermerodz/input-otp)
> fix: autofocus input-otp when component loads

- mobile/src/utils/channel/ChannelListProvider.tsx
- raven-app/src/utils/channel/ChannelListProvider.tsx
Unread channel count data was not being updated when the channel list was updated. So even though the unread count event was received, it was not updating it since it did not find it in the unread count list.
Fixed now:
https://github.com/The-Commit-Company/Raven/assets/19825455/4800b50f-a605-453d-bad1-37584e306fda
> fix: update unread channel counts when channel list is updated

- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Link.tsx
If no description is found, do not show the link preview. 
If no image is found, do not show skeleton loader.
> fix: do not show preview links if not available

- raven-app/src/components/feature/channel-details/ChannelDetails.tsx
- raven-app/src/components/feature/channel-settings/change-channel-type/ChangeChannelTypeButton.tsx
- raven-app/src/components/feature/channel-settings/change-channel-type/ChangeChannelTypeModal.tsx
- raven/api/chat.py
If you are a channel admin, you get the ability to change the channel type:
Open can be converted to Public or Private
Private can be converted to Open or Public
Public can be converted to Private or Open
> feat: allow changing of channel types for channel admins

- mobile/src/components/features/chat-space/MessageActions/MessageActionModal.tsx
- mobile/src/components/features/chat-space/MessageActions/MessagePreview.tsx
- mobile/src/components/features/chat-space/MessageActions/RetractVoteAction.tsx
- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
- raven-app/src/components/feature/chat/ChatMessage/MessageActions/MessageActions.tsx
- raven-app/src/components/feature/chat/ChatMessage/MessageActions/RetractVote.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/PollMessage.tsx
- raven/api/chat.py
- raven/api/raven_poll.py
- raven/permissions.py
- raven/raven_integrations/doctype/raven_scheduler_event/raven_scheduler_event.py
- raven/raven_integrations/doctype/raven_webhook/raven_webhook.py
- raven/raven_messaging/doctype/raven_poll_vote/raven_poll_vote.json
Added ability to retract vote for a poll in both mobile and web app. 
(will make this configurable via poll settings later, so this will be available when allowed by poll creator, this can be allowed by default)
> feat: retract vote in poll

- mobile/src/components/features/chat-space/MessageActions/MessageActionModal.tsx
- mobile/src/components/features/chat-space/MessageActions/PollActions.tsx
- mobile/src/components/features/chat-space/MessageActions/RetractVoteAction.tsx
- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
- mobile/src/components/features/polls/ViewPollVotes.tsx
- raven/api/raven_poll.py
> feat: show users who have voted for non anonymous polls (mobile app)

- raven-app/src/components/feature/chat/ChatInput/FileInput/useFileUpload.ts
- raven-app/yarn.lock
Was an easy fix:
Callback function passed to Tiptap has a state dependency. If the callback was added as a dependency to Tiptap's `useEditor` hook, it would cause rerenders (and hence also lose focus).
Solution:
Just store the file array in a ref
> fix(web): upload files on hitting enter

- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
Max width was causing an issue. Should work fine now since we scale the height if the width is greater than 280px.
> fix: maintain aspect ratio of image on mobile even with max width

- mobile/src/hooks/useUnreadCount.ts
- mobile/src/pages/direct-messages/DirectMessageList.tsx
- mobile/src/types/RavenChannelManagement/RavenChannel.ts
- mobile/src/utils/channel/ChannelListProvider.tsx
- mobile/yarn.lock
- raven-app/src/hooks/useUnreadMessageCount.ts
- raven-app/src/types/RavenChannelManagement/RavenChannel.ts
- raven-app/src/utils/channel/ChannelListProvider.tsx
- raven/api/raven_channel.py
- raven/raven_channel_management/doctype/raven_channel/raven_channel.json
- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
- types/RavenChannelManagement/RavenChannel.ts
Channels and DMs are sorted by the last message timestamp.
Added new fields in Raven Channel to store the last timestamp and the details of the last message.
> fix: sort channels and DMs by last message timestamp

- raven-app/src/components/feature/chat/ChatMessage/Renderers/PollMessage.tsx
- raven-app/src/components/feature/polls/ViewPollVotes.tsx
> feat: added view poll votes modal in web app

- mobile/src/components/features/chat-space/ChatInterface.tsx
- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
Three changes:
1. Enable scroll events on IonContent for chat stream.
2. Use a ref for checking if the user is scrolling inside the long press callback
3. Hide the background when the user is scrolling on hover/active state of message block
> fix: disable long press when scrolling on mobile app

- raven-app/src/components/feature/channels/ChannelList.tsx
- raven-app/src/components/feature/channels/CreateChannelModal.tsx
- raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx
- raven-app/src/components/feature/chat/ChatMessage/MessageItem.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- raven-app/src/components/feature/direct-messages/DirectMessageList.tsx
- raven-app/src/components/layout/Sidebar/SidebarComp.tsx
1. Tightened up the spacing on the channel caret icon
2. Made the unread count badge less "important"
3. Fixed font size of editor
> fix: consistent font sizes and icon alignment

- mobile/src/pages/direct-messages/DirectMessageList.tsx
Had a conditional that checked whether the DM user has a channel - hence sorting was broken.
> fix: DM sorting by last message on mobile

- mobile/package.json
- mobile/src/components/features/chat-space/chat-view/MessageBlock.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/Blockquote.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/Bold.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/Link.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/Mention.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/TiptapRenderer.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/Underline.tsx
- mobile/yarn.lock
> fix: use tiptap renderer on mobile app

- mobile/src/types/RavenMessaging/RavenMessage.ts
- raven-app/src/components/feature/chat/ChatMessage/MessageItem.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Link.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- raven-app/src/types/RavenMessaging/RavenMessage.ts
- raven/api/chat_stream.py
- raven/api/preview_links.py
- raven/raven_messaging/doctype/raven_message/raven_message.json
- raven/raven_messaging/doctype/raven_message/raven_message.py
- types/Messaging/Message.ts
Similar to Slack, hide preview links by clicking on the button.
> feat: add option to hide link preview

- mobile/src/components/common/EmojiPicker.tsx
- mobile/src/components/features/chat-input/EmojiList.tsx
- mobile/src/components/features/chat-input/EmojiSuggestion.tsx
- mobile/src/components/features/chat-input/Tiptap.tsx
- mobile/src/components/features/chat-space/chat-view/components/TiptapRenderer/TiptapRenderer.tsx
- raven-app/package.json
- raven-app/src/components/common/EmojiPicker/EmojiPicker.tsx
- raven-app/src/components/feature/chat/ChatInput/EmojiList.tsx
- raven-app/src/components/feature/chat/ChatInput/EmojiSuggestion.tsx
- raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx
- raven-app/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- raven-app/yarn.lock
Added support for emoji suggestions via the `:` key. This is available on both web and mobile.
By default, on typing ":", we show frequently used emojis. The emojis are fetched from the same database (emoji-picker-element), so anytime a new emoji is selected (either from suggestions, or from the emoji picker (button/reactions)), we increment the count of it's usage. This data is maintained in IndexedDB by emoji-picker-element - hence not shared across browsers.
Also fixed a bug (regression of #869) where the code and code block plugins were initialised multiple times. 
This PR also fixes a FIXME added earlier related to the keyboard handler extension conflicting with the mention extensions. Simply reordering the extensions in the editor initialisation fixed the issue.
> feat: emoji suggestions

- mobile/src/components/features/chat-input/FileUploadModal.tsx
Solution:
- Checked whether the channel is DM, or self or general channel and generated message accordingly.
- Note: Check if the description for self-message seems appropriate?
> fix: generate description message for file upload

- raven-app/src/components/feature/channels/ChannelList.tsx
- raven-app/src/components/feature/channels/CreateChannelModal.tsx
- raven-app/src/components/feature/direct-messages/DirectMessageList.tsx
- raven-app/src/components/layout/Sidebar/PinnedChannels.tsx
- raven-app/src/components/layout/Sidebar/SidebarBody.tsx
- raven-app/src/components/layout/Sidebar/SidebarComp.tsx
The sidebar was too "crowded". Too many icons - and always shown.
1. Expand and collapse buttons are only shown on hover and are moved to the right.
2. Add button is also moved to the right - and only shown on hover
3. Clicking on "Channels" or "Members" also toggles the list
4. Removed icon for pinned messages
5. Added animation for collapsing and expanding groups (will be used when we add channel groups as well)
6. Transition added for unread count badge
Before:
After:
> fix(ui): changed layout of sidebar with transitions

- raven-app/package.json
- raven-app/src/App.tsx
- raven-app/src/components/feature/chat/ChatStream/useChatStream.ts
- raven-app/src/pages/auth/Login.tsx
- raven-app/src/utils/auth/UserProvider.tsx
- raven-app/yarn.lock
- raven/yarn.lock
SWR provides a way to use a custom cache provider. We now store the API calls in local storage as soon as the user reloads the page/exits the tab. 
Example below with each API call throttled by 1 second:
Without cache (approx 12 seconds):
With cache (near instant):
The API calls are still being made - but since the results are cached, we're able to show the UI instantly. We still need to cache the APIs on the backend though.
Next steps:
1. Avoid network request waterfalls (currently fetching users > channels > members > messages). We can remove all Context and reduce number of re-renders - just use SWR hooks directly and load everything in parallel.
2. Avoid layout shifts when loading - remove all spinners and replace with perfectly sized skeleton loaders/boxes.
> feat: cache data locally

- raven-app/src/components/common/UserAvatar.tsx
- raven-app/src/components/feature/channels/ChannelList.tsx
- raven-app/src/components/feature/channels/CreateChannelModal.tsx
- raven-app/src/components/feature/chat/ChatInput/Tiptap.tsx
- raven-app/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
- raven-app/src/components/feature/chat/ChatStream/ChatStream.tsx
- raven-app/src/components/feature/direct-messages/DirectMessageList.tsx
- raven-app/src/components/layout/Sidebar/SidebarComp.tsx
- raven-app/tailwind.config.js
1. Added new animation timing functions for hover and loading. 
2. Avoid layout shift in sidebar - pre-calculate the height of the sidebar sections if possible (data is cached anyway)
3. Remove lazy loading of Tiptap editor - we need it anyway
Before (layout shifts even with caching):
After (almost no layout shift):
Next steps:
1. Remove network request waterfall
2. Use skeleton loader or just the Raven logo for the main full page loader (splash screen)
> fix: animation timing and layout shifting

- raven/api/raven_message.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
Publish temp socket events for the desk interface. Will remove them once Desk interface integration has been updated.
Closes #905
> fix: added temp events for desk interface

- raven-app/src/utils/users/UserListProvider.tsx
- raven/api/raven_users.py
- raven/raven/doctype/raven_user/raven_user.py
User List is cached on Redis.
Fetching 3524 Raven Users via `raven_users.get_list` API (averages over 10 runs)
Before: 120ms 
After: 20ms
Savings per request here does not matter as much but multiple concurrent users trying to access Raven at the same time will not hit the database to fetch the same list of users.
> perf: cache user list

- raven-app/src/components/feature/saved-messages/SavedMessages.tsx
- raven-app/src/components/layout/Sidebar/SidebarFooter.tsx
1. Added menu for user to set their availability status, this can be reset by the user.
2. Added modal for the user to add a custom status. This will be shown in the user's hover card as well as the user's header in DM channel.
> 131 user should be able to set their availability status

- raven-app/src/components/feature/chat/ChatMessage/Renderers/DoctypeLinkRenderer.tsx
- raven-app/src/hooks/useDoctypePreview.ts
- raven/api/document_link.py
- Preview Doctype links inside chat.
- Create hook and api for doctype preview.
- Add copy to clipboard, copy link and open in new tab functionality.
- Handle Error and Loading states.
> feat: add doctype preview card

- frontend/src/components/layout/EmptyState/EmptyState.tsx
> fix: make saved messages header mobile responsive

- raven/patches.txt
- raven/patches/v1_6/migrate_older_raven_users.py
Raven Users created earlier did not have any "type" set. This patch adds a "type" of "User" to those.
> fix: migrate older Raven Users with type set to "User"

- frontend/src/components/feature/CommandMenu/DMChannelItem.tsx
- frontend/src/components/feature/CommandMenu/UserList.tsx
- frontend/src/components/feature/chat-header/DMChannelHeader.tsx
- frontend/src/components/feature/direct-messages/DirectMessageList.tsx
- frontend/src/components/layout/EmptyState/EmptyState.tsx
- frontend/src/utils/operations.ts
This is somewhat of a fix for #979 - at least the app does not crash.
Not sure if we should delete all DMs of Raven Users who are deleted or not.
> fix: show "deleted user" if Raven User not found

- frontend/src/components/feature/CommandMenu/DMChannelItem.tsx
- frontend/src/components/feature/CommandMenu/UserList.tsx
- frontend/src/components/feature/chat-header/DMChannelHeader.tsx
- frontend/src/components/feature/direct-messages/DirectMessageList.tsx
- frontend/src/components/layout/EmptyState/EmptyState.tsx
- raven/raven/doctype/raven_user/raven_user.py
1. If the "User" is disabled, disable the "Raven User".
2. If the Raven User is disabled, then do not show it on the sidebar. (Still searchable in the command menu)
> fix: do not show disabled users in the sidebar

- frontend/package.json
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/Mention.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/tiptap-renderer.styles.css
- yarn.lock
Channel mentions show up with a link in messages now.
> fix: channel mentions with link

- frontend/src/components/layout/Sidebar/SidebarHeader.tsx
Show the search button in the header so that users can find it. Added a tooltip to mention the keyboard shortcut as well.
> fix(ux): show search button

- frontend/src/components/feature/userSettings/PushNotifications/PushNotificationToggle.tsx
Enabling push notifications takes time, hence when the user clicks on "Enable", they have to wait for the confirmation to show up. This PR adds a promise based toast when enabling push notifications to show a loading spinner when the request is being processed.
> fix: show loading toast when enabling push notifications

- frontend/src/components/feature/chat/ChatInput/RightToolbarButtons.tsx
- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
Used the JSON to find empty paragraphs at the end of the message and set the content in the editor after removing those sections.
Before and after:
> fix: remove trailing empty paragraphs when sending messages

- frontend/src/components/feature/channel-details/edit-channel-description/EditChannelDescriptionModal.tsx
- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/feature/channels/CreateChannelModal.tsx
- frontend/src/components/feature/direct-messages/DirectMessageList.tsx
- frontend/src/components/feature/userSettings/AvailabilityStatus/SetUserAvailabilityMenu.tsx
- frontend/src/components/feature/userSettings/CustomStatus/SetCustomStatusContent.tsx
- frontend/src/components/feature/userSettings/PushNotifications/PushNotificationToggle.tsx
- frontend/src/components/feature/userSettings/SettingsSidebar.tsx
- frontend/src/components/feature/userSettings/UploadImage/DeleteImageModal.tsx
- frontend/src/components/feature/userSettings/UploadImage/FileUploadBox.tsx
- frontend/src/components/feature/userSettings/UploadImage/ImageUploader.tsx
- frontend/src/components/feature/userSettings/UploadImage/UploadImageModal.tsx
- frontend/src/components/feature/userSettings/UserProfile/UserProfile.tsx
- frontend/src/components/layout/Sidebar/PinnedChannels.tsx
- frontend/src/components/layout/Sidebar/SidebarBody.tsx
- frontend/src/components/layout/Sidebar/SidebarComp.tsx
- frontend/src/components/layout/Sidebar/SidebarFooter.tsx
- frontend/src/components/layout/Sidebar/SidebarHeader.tsx
- frontend/src/pages/settings/Integrations/FrappeHR.tsx
- frontend/src/pages/settings/Settings.tsx
- frontend/src/utils/translations.ts
I have added the setup & utilities for translations. 
All frontend strings need to be wrapped as `__("My String")` or with variables: `__("My String of length {0}", ["10"])`
PO files generated are only for doctype/backend related files - so we need to see how we can extend it to .tsx files. 
Will add more translatable strings gradually.
Closes #356
> feat: translations

- frontend/src/components/feature/chat/ChatInput/tiptap.styles.css
- frontend/src/components/feature/settings/ai/bots/BotDocs.tsx
- frontend/src/components/feature/settings/ai/bots/BotForm.tsx
- frontend/src/components/layout/CodeBlock.tsx
- raven/raven_bot/doctype/raven_bot/raven_bot.py
Added inline documentation for Raven Bots. Will also create a Wiki.
> feat: inline docs for Raven Bots

- frontend/src/App.tsx
- frontend/src/pages/NotFound.tsx
> feat: 404 page

- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
Open channels did not have any admin members earlier. Added this so that open channels could be converted/deleted/archived.
> fix: create channel member for open channels

- frontend/src/components/feature/channel-member-details/remove-members/RemoveChannelMemberModal.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
- frontend/src/components/feature/chat/ChatMessage/SystemMessageBlock.tsx
- frontend/src/components/feature/chat/ChatStream/ChatStream.tsx
- frontend/src/components/feature/chat/ChatStream/useChatStream.ts
- raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py
- raven/raven_messaging/doctype/raven_message/raven_message.json
- raven/raven_messaging/doctype/raven_message/raven_message.py
- types/Messaging/Message.ts
> feat: show system messages when channel members are changed

- frontend/src/components/common/LinkField/LinkField.tsx
- frontend/src/components/feature/CommandMenu/SettingsList.tsx
- frontend/src/components/feature/chat/ChatInput/DocumentLinkButton.tsx
- frontend/src/components/feature/chat/ChatInput/RightToolbarButtons.tsx
- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
- frontend/src/components/feature/chat/ChatMessage/ActionModals/AttachFileToDocumentModal.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
- frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
- frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx
- frontend/src/hooks/useRecentlyUsedDocType.ts
Attach documents like Purchase Invoice etc right from Raven:
You also get to preview the document before sending it. 
Another small improvement: recently used doctypes come up first in the dropdown since in most cases users are going to only use a few of them and hence they don't have to type the doctype name.
> feat: attach docs from Raven

- frontend/package.json
- frontend/src/components/feature/chat/ChatInput/useSendMessage.ts
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TimestampRenderer.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/TiptapRenderer.tsx
- frontend/src/utils/dateConversions/utils.ts
- raven/raven_messaging/doctype/raven_message/raven_message.py
- yarn.lock
This PR detects "time" in any human readable format when a message is sent and embeds a timestamp in the message. When receivers see the message, they can hover over the timestamp to view it in their timezone.
Also works with arbritary time
> feat: show embedded timestamps in messages

- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
- frontend/src/components/feature/chat/ChatInput/TypingIndicator/TypingIndicator.tsx
- frontend/src/components/feature/chat/ChatInput/TypingIndicator/useTypingIndicator.ts
- frontend/src/components/feature/chat/ChatMessage/Renderers/DoctypeLinkRenderer.tsx
- frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
- frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx
- frontend/tailwind.config.js
- raven/ai/functions.py
- raven/ai/handler.py
- realtime/handlers.js
This PR adds a typing indicator when users start typing in a channel. 
1. When a user opens a channel, a socketIO event `raven_channel_get_typers` is emitted. See `useTypingIndicator.ts`
2. The socketIO handler in the backend then checks the permission for the user for that channel, and sends back a list of current active "typers" via an event `raven_channel_typers`. This event is only sent to the user who requested it - via the user room already available in Frappe.
3. When a user starts typing, a socketIO event `raven_channel_typing` is emitted by the client side. See `useTyping` in `useTypingIndicator.ts`.  To avoid multiple events being sent when the user types fast, this is throttled and only one event is sent for as long as the user types. 
4. On receiving the typing event, the …
> feat: typing indicator

- frontend/src/components/feature/channel-groups/UnreadList.tsx
- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/feature/direct-messages/DirectMessageList.tsx
- frontend/src/components/layout/Sidebar/PinnedChannels.tsx
- frontend/src/components/layout/Sidebar/SidebarBody.tsx
- frontend/src/components/layout/Sidebar/useGetChannelUnreadCounts.ts
- raven/api/raven_channel.py
1. Create a new `UnreadList` component that displays channels and DMs with unread messages.
2. Filter out unread items from the existing `ChannelList` and `DirectMessageList` components to avoid duplicates.
3. Do not show the `UnreadList` section when there are no unread messages.
> feat: added a section for 'unread' messages in the sidebar

- frontend/src/components/feature/chat/ChatMessage/LeftRightLayout/LeftRightLayout.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
- frontend/src/pages/settings/Appearance.tsx
- raven/boot.py
> fix: default value for chat layout style

- frontend/src/components/feature/chat/ChatMessage/ReplyMessageBox/ReplyMessageBox.tsx
> fix: set correct `max-width` to replied message content

- frontend/src/App.tsx
- frontend/src/components/feature/channel-settings/archive-channel/ArchiveChannelModal.tsx
- frontend/src/components/feature/chat-header/ChannelHeader.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/FileMessage.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/LinkPreview.tsx
- frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
- frontend/src/components/feature/chat/chat-footer/ArchivedChannelBox.tsx
- frontend/src/components/feature/chat/chat-footer/JoinChannelBox.tsx
- frontend/src/components/layout/Heading/PageHeader.tsx
- frontend/src/components/layout/Sidebar/WorkspacesSidebar.tsx
- frontend/src/components/layout/WorkspaceSwitcherGrid.tsx
- frontend/src/main.tsx
- frontend/src/pages/settings/Settings.tsx
- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
> fix: miscellaneous fixes on UI

- raven/raven_messaging/doctype/raven_message/raven_message.py
Closes #1186
Bug introduced because of caching channel members
> fix: AI bot handler uses user_id to fetch bot doc

- frontend/src/components/feature/chat/ChatMessage/Renderers/DoctypeLinkRenderer.tsx
- raven/api/document_link.py
Instead of fetching the document link on clicking the copy/open link button, we now send it with the doctype preview itself. This should fix #1193
> fix(web): send document links with doctype preview

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/common/EmojiPicker/EmojiPicker.tsx
- frontend/src/components/feature/chat/ChatInput/ChannelMentionList.tsx
- frontend/src/components/feature/chat/ChatInput/EmojiList.tsx
- frontend/src/components/feature/chat/ChatInput/EmojiSuggestion.tsx
- frontend/src/components/feature/chat/ChatInput/MentionList.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/EmojiPickerButton.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageReactions.tsx
- yarn.lock
Replace emoji-picker-element with emoji-mart
Why?
1. Emojis will be rendered consistently across operating systems. Windows emojis are weird, hence this will use Apple's emoji palette for all operating systems.
2. Will allow us to add custom emojis to the main palette.
> feat: add emoji-mart for emoji picker

- frontend/src/App.tsx
- frontend/src/components/feature/DocumentPreviewToolConfigurator.tsx
- frontend/src/components/feature/userSettings/SettingsSidebar.tsx
- frontend/src/hooks/useDoctypeMeta.ts
- frontend/src/pages/settings/Integrations/DocumentPreviewTool.tsx
- raven/api/document_link.py
Allow users to configure document link previews easily from Raven.
Select a DocType to view it's fields and a live preview (last doc is automatically selected - users can change documents to view their previews).
Users can select fields that they want to see in the preview and click on the update button. This will then create or delete property setters and update the doctype meta as well as the preview.
> feat: configure document previews

- frontend/src/App.tsx
- frontend/src/components/common/EmojiPicker/AddCustomEmojiDialog.tsx
- frontend/src/components/common/EmojiPicker/DeleteCustomEmojiDialog.tsx
- frontend/src/components/common/EmojiPicker/EmojiPicker.tsx
- frontend/src/components/feature/DocumentPreviewToolConfigurator.tsx
- frontend/src/components/feature/chat/ChatInput/EmojiSuggestion.tsx
- frontend/src/components/feature/chat/ChatInput/RightToolbarButtons.tsx
- frontend/src/components/feature/chat/ChatMessage/ActionModals/ReactionAnalyticsModal.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/MessageReactionAnalytics.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/EmojiPickerButton.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageReactions.tsx
- frontend/src/components/feature/userSettings/SettingsSidebar.tsx
- frontend/src/components/feature/userSettings/UploadImage/FileUploadBox.tsx
- frontend/src/components/feature/workspaces/AddWorkspaceForm.tsx
- frontend/src/pages/settings/CustomEmojis/CustomEmojiList.tsx
- frontend/src/types/RavenMessaging/RavenCustomEmoji.ts
- frontend/src/types/RavenMessaging/RavenMessageReaction.ts
- raven/api/reactions.py
- raven/raven_messaging/doctype/raven_custom_emoji/raven_custom_emoji.js
- raven/raven_messaging/doctype/raven_custom_emoji/raven_custom_emoji.json
- raven/raven_messaging/doctype/raven_custom_emoji/raven_custom_emoji.py
- raven/raven_messaging/doctype/raven_custom_emoji/test_raven_custom_emoji.py
- raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.json
- raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.py
Added support for using custom emojis in reactions on the web app.
PNGs, GIFs and JPGs supported.
Added a new checkbox in the Reactions doctype for "is_custom". If it's a custom emoji, we do not need to escape the characters and instead store the "name" of the emoji in the `reaction_escaped` field. This is then used to show the "name" of the reaction in the tooltip.
> feat(web): custom emojis

- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/layout/Sidebar/WorkspacesSidebar.tsx
Workspace icons have randomly generated colors based on their name. The side element to denote the current selected workspace has also been increased.
> fix(web): colors for workspaces and improved visibility

- frontend/package.json
- frontend/src/components/feature/chat/ChatInput/MobileActions/CreatePollDrawer.tsx
- frontend/src/components/feature/chat/ChatInput/MobileActions/MobileInputActions.tsx
- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
- frontend/src/components/layout/Drawer.tsx
- yarn.lock
The `<Drawer />` component from Vaul on the PWA had two issues:
1. Compatibility with peer dependency of Radix-ui - this has been fixed now.
2. After closing the drawer, a `pointer-events:none` style was set on the body. Added a temporary workaround for this now. Refer: https://github.com/emilkowalski/vaul/issues/492
> fix: drawers on mobile PWA

- frontend/package.json
- frontend/src/components/layout/Drawer.tsx
- yarn.lock
We have 3 libraries that depend on RadixUI - Radix Themes, Vaul (for the drawer), and CMDK. The version of the Radix Dialog package needs to be set to the same value to prevent issues.
This PR fixes two issues:
1. Opening drawers on mobile were causing the application to crash. This was earlier fixed by #1281 but on closing the drawer the application used to freeze.
2. Even on a regular dialog on desktop, the application used to freeze because `pointer-events: none` was set on the body.
References: https://github.com/radix-ui/themes/issues/155 and https://github.com/radix-ui/primitives/issues/3317
Closes #1288
> fix: dialog and drawer freezing on close

- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
Members are now fetched from a ref instead of memo.
Closes #1284
> fix: update member suggestions in realtime in the editor

- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/feature/channels/CreateChannelModal.tsx
- frontend/src/utils/channel/ChannelListProvider.tsx
- frontend/src/utils/users/UserListProvider.tsx
- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
- raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py
Added a new real-time event for channel list update since it was not being updated when a member was added to a private channel.
Also added revalidation on focus for mobile devices.
Closes #1299
> fix: update channel list via realtime events

- frontend/public/frappe-push-notification.js
- frontend/src/types/Raven/RavenPushToken.ts
- frontend/src/types/Raven/RavenSettings.ts
- raven/api/notification.py
- raven/raven/doctype/raven_push_token/raven_push_token.js
- raven/raven/doctype/raven_push_token/raven_push_token.json
- raven/raven/doctype/raven_push_token/raven_push_token.py
- raven/raven/doctype/raven_push_token/test_raven_push_token.py
- raven/raven/doctype/raven_settings/raven_settings.json
- raven/raven/doctype/raven_settings/raven_settings.py
Added a new DocType "Raven Push Token" which stores the FCM tokens before sending it to Frappe Cloud's relay service. API on the service worker for push notifications has been changed to point to new APIs in Raven.
> feat: store push notification token on site

- frontend/public/frappe-push-notification.js
- frontend/src/types/Raven/RavenPushToken.ts
- frontend/src/types/Raven/RavenSettings.ts
- raven/api/notification.py
- raven/raven/doctype/raven_push_token/raven_push_token.js
- raven/raven/doctype/raven_push_token/raven_push_token.json
- raven/raven/doctype/raven_push_token/raven_push_token.py
- raven/raven/doctype/raven_push_token/test_raven_push_token.py
- raven/raven/doctype/raven_settings/raven_settings.json
- raven/raven/doctype/raven_settings/raven_settings.py
Added a new DocType "Raven Push Token" which stores the FCM tokens before sending it to Frappe Cloud's relay service. API on the service worker for push notifications has been changed to point to new APIs in Raven.
> feat(notifications): store push notification token on site

- frontend/src/components/feature/channel-member-details/add-members/AddMembersButton.tsx
- raven/api/raven_channel_member.py
We used to allow this earlier, but I had added a permission check for channel write on adding members. Removing that fixed the issue.
> fix: allow non-admins to add members to private channels

- frontend/src/components/feature/channels/CreateChannelModal.tsx
- frontend/src/components/feature/workspaces/AddWorkspaceForm.tsx
- frontend/src/components/feature/workspaces/WorkspaceEditForm.tsx
- frontend/src/types/Raven/RavenWorkspace.ts
- raven/api/workspaces.py
- raven/permissions.py
- raven/raven/doctype/raven_workspace/raven_workspace.json
- raven/raven/doctype/raven_workspace/raven_workspace.py
- raven/tests/test_permissions.py
By default, any workspace member can create channels in a workspace. 
If users want only admins to be allowed to create channels in a workspace, they can do so by checking the "Only admins can create channels in this workspace" setting. This is available on both the create workspace and edit workspace flow.
> feat: allow anyone to create channels in a workspace

- frontend/src/components/feature/userSettings/UploadImage/UploadImageModal.tsx
- frontend/src/components/feature/workspaces/AddWorkspaceForm.tsx
- raven/api/upload_file.py
Changes:
1. Store the Unique URL instead of file URL for profile, workspace and messages
2. Compress images for workspace
cc: @ankush
> perf: use unique URL in files instead of file URL

- frontend/src/components/feature/chat/ChatMessage/Renderers/DateTooltip.tsx
> fix: align system messages

- frontend/src/components/feature/chat/ChatInput/FileInput/useFileUpload.ts
- frontend/src/components/feature/chat/ChatInput/useSendMessage.ts
- frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx
- frontend/src/components/feature/chat/ChatStream/ChatStream.tsx
- frontend/src/components/feature/chat/ChatStream/useChatStream.ts
- frontend/src/hooks/useActiveSocketConnection.ts
- frontend/src/pages/MainPage.tsx
- frontend/src/types/RavenMessaging/RavenMessage.ts
- raven/api/raven_message.py
- raven/api/upload_file.py
On sending a message, we update the chat stream with the new message as soon as we get a response from the API call. This isn't optimistic )we still wait for the API call), but it's much better UX wise since we don't need to wait for the web socket event to be broadcast and received.
If websocket is not connected, Raven will try reconnect automatically (max 3 times), and if that fails, we show a toast for 5 seconds asking the user to refresh.
> perf: update message stream without waiting for websocket event

- frontend/src/components/feature/chat/ChatInput/EmojiSuggestion.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx
Uses emoji-mart's favourites menu (limited to 4) - does not include any custom emojis (for now). This would be dependent on the browser though, so the suggestions on mobile and web would differ. We probably need to allow this to be user configurable at some point.
> feat: suggest frequently used emojis in quick reactions

- frontend/src/components/feature/channel-groups/UnreadList.tsx
- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/layout/Sidebar/SidebarBody.tsx
- frontend/src/components/layout/Sidebar/useGetChannelUnreadCounts.ts
Users can now choose if they wish to see all channels (including public channels that they are not a member of) or just their own channels. This is persisted in local storage.
Unread counts for channels where they are not a member of is not shown (neither fetched)
https://github.com/user-attachments/assets/e3c095dc-4e81-4f1e-983f-d2d4cf0d2f41
> feat: add toggle in sidebar for showing/hiding all channels

- frontend/src/components/feature/chat/ChatMessage/LeftRightLayout/LeftRightLayout.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/QuickActions/QuickActions.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageItem.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageReactions.tsx
- frontend/src/components/layout/Sidebar/useGetChannelUnreadCounts.ts
- frontend/src/hooks/usePostMessageReaction.ts
On reacting to a message, raven will first update the cache optimistically, then wait for the response from the server and if the response is Ok, it will update the message in the cache. If the response is an error, it will rollback.
Post this, when the websocket event comes in for the reaction, the message will be updated anyway, so if there are multiple people reacting, it will reflect the correct value
> perf: optimistic updates for reactions

- frontend/src/components/feature/GlobalSearch/MessageSearch.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/MessageActions.tsx
- frontend/src/components/feature/chat/ChatMessage/Renderers/TiptapRenderer/LinkPreview.tsx
- frontend/src/components/feature/chat/ChatStream/ChatStream.tsx
- frontend/src/components/feature/chat/ChatStream/useChatStream.ts
- raven/api/search.py
Added a skeleton loader for link previews of similar height - this was the primary cause of the janky scroll since the content loaded after the messages were rendered.
Also added a resize observer to the main container - if the user is within 100px of the bottom, we automatically scroll to the bottom if the content resizes.
When loading older messages, we were earlier restoring the scroll position by scrolling to the last message. This has been made much smoother - we now restore the last scroll position instead
Closes #1158
> fix: janky scroll in chat stream when content loads

- frontend/src/components/feature/chat/ChatInput/EmojiSuggestion.tsx
- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
For emojis: allow any preceding character
For user and channel mentions - allow any preceding character except a letter a digit since users would type in emails etc. Brackets, hyphens etc would work.
Reference: https://tiptap.dev/docs/editor/api/utilities/suggestion#allow
> fix: allow user and channel mentions without preceding space

- frontend/src/components/feature/chat/ChatMessage/Renderers/DoctypeLinkRenderer.tsx
Description:
Sanitize HTML content before rendering it in Doctype link message
Output:
before
after
> fix: remove html tags in doctype link renderer

- frontend/src/App.tsx
- frontend/src/components/feature/chat/ChatInput/Tiptap.tsx
- frontend/src/components/feature/userSettings/SettingsSidebar.tsx
- frontend/src/pages/settings/Preferences.tsx
- frontend/src/utils/preferences.ts
Preference is stored in local storage so users would need to configure this on any new device _(for now)_
> feat: allow users to configure Enter key behaviour

- frontend/src/components/feature/chat/ChatMessage/Renderers/ThreadMessage.tsx
- frontend/src/pages/MainPage.tsx
- raven/api/threads.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
- raven/utils.py
If a thread message came up on the main channel's chat stream, we used to:
1. Fetch the number of replies using the `frappe.client.get_count` API without caching since it was using a filter.
2. Subscribe to the "Raven Message" document - this would then lead to permission checks etc
3. Anytime a new thread reply came in, we called the same API.
If there were a 100 users on a channel, they would all independently fetch the count + subscribe to the Raven Message + then if a new message came in, all of them would fetch the count again.
Yes, I know.
If a thread message is on the main channel's chat stream:
1. Fetch the number of replies - cached in the backend as well.
2. No subscription to Raven Message
3. Anytime a new thread reply came in, the websocket event has the new reply count and we …
> perf: cache number of thread replies

- .github/workflows/ci.yml
- frontend/src/components/feature/GlobalSearch/MessageSearch.tsx
- frontend/src/components/feature/channels/ChannelList.tsx
- frontend/src/components/feature/chat/ChatMessage/MessageActions/MessageActions.tsx
- frontend/src/components/feature/chat/ChatStream/useChatStream.ts
- frontend/src/components/feature/message-actions/MessageActionVariableBuilder.tsx
- frontend/src/components/feature/saved-messages/SavedMessages.tsx
- frontend/src/components/layout/Sidebar/MentionsButton.tsx
- frontend/src/pages/ChatSpace.tsx
- raven/api/message_actions.py
- raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py
Copy links of messages to be shared on other platforms. Works for threads as well - it will open the thread in the thread explorer page.
https://github.com/user-attachments/assets/75d41034-b0a3-496d-b92a-701ccf6ca4a5
This also works with Message Actions - example: autofilling the reference of a support ticket
Closes #1447
> feat: shareable message links

- apps/mobile/app/[site_id]/_layout.tsx
- apps/mobile/lib/FrappeNativeProvider.tsx
- apps/mobile/package.json
- yarn.lock
SWR config is set up to listen to both network and "focus" states - API calls will be revalidated when network is restored or when app is brought back into focus.
> feat(mobile): setup SWR config for React Native

- apps/mobile/app/[site_id]/_layout.tsx
- apps/mobile/lib/FrappeNativeProvider.tsx
Set an interval of 5 minutes - refresh tokens that are going to expire in the next 7 minutes. (These values can be tweaked later.) This prevents APIs from failing while using the mobile app.
> feat(mobile): automatically refresh access tokens

- frontend/src/components/feature/message-actions/MessageActionForm.tsx
- frontend/src/pages/settings/MessageActions/ViewMessageAction.tsx
- frontend/src/types/RavenIntegrations/RavenMessageAction.ts
- raven/api/message_actions.py
- raven/raven_integrations/doctype/raven_message_action/raven_message_action.json
- raven/raven_integrations/doctype/raven_message_action/raven_message_action.py
Added a new option for Server Scripts in Message Actions.
Also added inline docs:
> feat: add support for server scripts in Message Actions

- apps/mobile/app/[site_id]/_layout.tsx
After refreshing OAuth tokens, we need to revoke the existing ones else they are always marked as "Active" and are not removed from the database periodically.
https://discuss.frappe.io/t/oauth-2-provider-for-frappe-apps/15652/19
@prathameshkurunkar7
> fix(mobile): revoke old tokens after refreshing

- raven/api/raven_message.py
- raven/api/raven_poll.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
1. Send last message details in realtime events for DMs
2. Strip empty spaces at the end of messages
3. Extract mentions using BS4 instead of Tiptop JSON
4. Save "content" in plain text and without markdown formatting
> fix: store content from HTML in plain text and not markdown

- frontend/index.html
- raven/www/raven.py
Will probably have a different field somewhere in Raven Settings to set a specific favicon + app logo later. Right now it just uses it from Website Settings
> feat(web): use favicon available in Website Settings

- apps/mobile/hooks/useFirebasePushTokenListener.ts
- apps/mobile/lib/Providers.tsx
When we switch sites, we need to get the push notification token and store it in the site. Maybe we don't need the toggle in the profile page for push notifications at all.
> feat(mobile): store push token for each site

- raven/api/raven_message.py
- raven/api/raven_mobile.py
- raven/notification.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
Speeds up sending messages since notifications will be sent after returning the message response
> perf: use after_response to send notifications

- raven/ai/functions.py
Hello,
I am trying to setup a simple process to allow users to query the help articles of a site.
I have created two functions for an assistant:
1. get_help_article_list: Get List for the doctype Help Article
2. get_help_docs: Get Multiple Documents for the doctype Help Article
I encountered two issues:
1. Issue importing frappe.client (Frappe version-15)
I propose to import it explicitely at the top of the file.
```python
Traceback (most recent call last):
File "apps/raven/raven/ai/handler.py", line 137, in handle_requires_action
function_output = get_document(function.reference_doctype, **args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/raven/raven/ai/functions.py", line 10, in get_document
return frappe.client.get(doctype, name=document_id)
^^^^^^^^^^^^^ …
```
> fix: function call and fields in get_list

- raven/permissions.py
If the list view in frappe desk is opened before workspaces or members are created, the following error occurs:
```
{
"erpnext": "15.58.1",
"frappe": "15.64.0",
"raven": "2.2.2"
}
```
```
List/Raven Workspace/List
```
```
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 115, in application
response = frappe.api.handle(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/api/__init__.py", line 49, in handle
data = endpoint(**arguments)
^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
return frappe.handler.handle()
^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/handler.py", line 51, in handle
data = execute_cmd(cmd)
^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/handler.py", line 84, in execute_cmd
return …
```
> fix: invalid query error if not workspaces or users exist

- raven/raven_bot/doctype/raven_bot/raven_bot.py
Fixes a bug where calling `frappe.throw(e)` with a non-string exception caused a `TypeError`, leading to a confusing error message for the user.
> fix: handle exception in openai assistant creation

- raven/raven_ai/doctype/raven_ai_function/raven_ai_function.py
**Description:**  
Fixes an issue where creating a Custom Function could throw a JSON error:
> the JSON object must be str, bytes or bytearray, not dict
Added a helper method `get_params_as_dict()` to safely handle both `dict` and `str` types for `params`.  
This improves Custom Function creation reliability and prevents type mismatch errors.
**Screenshot (Error Before Fix):**
> fix: handle dict and str types for params in Raven AI Function

- frontend/src/components/feature/threads/ThreadManager/ThreadsList.tsx
- frontend/src/pages/MainPage.tsx
Since we are using Infinite loading on the threads list, it made sense to just dispatch a custom event and listen to it if the threads list is mounted. This is performant since a new thread reply does not trigger a revalidation of the entire thread list.
> fix(web): update thread reply counts in realtime

- frontend/src/components/layout/CodeBlock.tsx
- Fixes runtime error when `navigator.clipboard` is undefined
- Adds fallback method for older or insecure browsers
- Adds "Copied" feedback with tooltip and icon
Clipboard copy was failing in some environments (e.g. HTTP or older browsers). This change makes the copy function more reliable and user-friendly.
**Before**
[before.webm](https://github.com/user-attachments/assets/c76192ae-0f97-4d2d-8458-48f4bada2b8c)
**After**
[after.webm](https://github.com/user-attachments/assets/edf571dd-ca33-4dd6-a099-dbb0474f5d4a)
> Fix clipboard copy error and add copied feedback

- frontend/src/App.tsx
- frontend/src/components/feature/settings/ai/bots/BotFileSources.tsx
- frontend/src/components/feature/settings/ai/bots/BotForm.tsx
- frontend/src/components/feature/settings/ai/file-sources/FileSourceUploadDialog.tsx
- frontend/src/components/feature/userSettings/SettingsSidebar.tsx
- frontend/src/components/feature/userSettings/UploadImage/FileUploadBox.tsx
- frontend/src/pages/settings/AI/FileSourcesList.tsx
- frontend/src/types/RavenAI/RavenAIBotFiles.ts
- frontend/src/types/RavenAI/RavenAIFileSource.ts
- frontend/src/types/RavenBot/RavenBot.ts
- raven/ai/ai.py
- raven/ai/openai_client.py
- raven/raven_ai/doctype/raven_ai_bot_files/raven_ai_bot_files.json
- raven/raven_ai/doctype/raven_ai_bot_files/raven_ai_bot_files.py
- raven/raven_ai/doctype/raven_ai_file_source/raven_ai_file_source.js
- raven/raven_ai/doctype/raven_ai_file_source/raven_ai_file_source.json
- raven/raven_ai/doctype/raven_ai_file_source/raven_ai_file_source.py
- raven/raven_ai/doctype/raven_ai_file_source/test_raven_ai_file_source.py
- raven/raven_bot/doctype/raven_bot/raven_bot.json
- raven/raven_bot/doctype/raven_bot/raven_bot.py
AI Agents can now accept files like HR Manuals, Spreadsheets and images for instructions. Based on the type of file, the AI Agent can either use ["File Search"](https://platform.openai.com/docs/assistants/tools/file-search) or ["Code Interpreter"](https://platform.openai.com/docs/assistants/tools/code-interpreter) on it.
Another improvement: earlier, in chats, the AI Agent could not parse PDFs which were not machine readable - like scans of invoices. With this new update, certain attachments are made available to both code interpreter as well as file search.
> feat(ai): file search for AI Agents

- frontend/src/components/feature/userSettings/UploadImage/FileUploadBox.tsx
- frontend/src/hooks/useGetFilePreviewUrl.ts
This PR adds audio file preview functionality to the FileUploadBox component:
- Supports audio playback (mp3, m4a) with play/pause toggle
- Updates useGetFilePreviewUrl hook to support audio preview types
- Existing image preview functionality is untouched and continues to work as expected
[Screencast from 2025-05-08 08-27-51.webm](https://github.com/user-attachments/assets/84a1035a-bf47-4b0e-9e3a-e0cd86be7708)
> Add audio preview with play/pause support in FileUploadBox

- raven/raven_channel_management/doctype/raven_channel/raven_channel.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
- raven/utils.py
Scenario:
User has the role "Raven User", but does not have access to the desk interface - hence is a "Website User".
Events that were being published to the room "all" were not being broadcasted to website users. This meant that thread reply counts, unread message counts, channel member updates were all being missed.
Fix:
Just send all events to the "doctype:Raven User" room (meant for list_update in Frappe Framework). Since all users are going to be subscribed to that room on app load anyway, it does not hurt. Seems to be working.
> fix: publish realtime events to room for Raven instead of "all"

- frontend/src/utils/operations.ts
- raven/api/reactions.py
- raven/patches.txt
- raven/patches/v2_4/add_unique_constraint_on_reactions.py
- raven/raven_messaging/doctype/raven_message_reaction/raven_message_reaction.py
Closes #1697 
When reacting to a message very quickly, the system was registering multiple reactions on the same message by the same user. 
The fix includes:
1. A unique constraint on three fields - owner, message and reaction in Raven Message Reaction
2. A patch that would add the constraint to existing sites + also remove duplicate reactions from messages before adding the constraint (else the patch would fail)
3. When reacting to a message, we first try inserting it - if it fails due to a unique validation error, we remove the reaction - this ensures atomicity (as opposed to first checking if a reaction exists and then deciding it)
4. When deleting a reaction, we now delete all reactions matching the criteria instead of just one like earlier.
5. When computing the final JSON to be …
> fix: add unique constraint to reactions to avoid race conditions

- frontend/src/components/feature/settings/ai/functions/FunctionConstants.ts
- frontend/src/components/feature/settings/ai/functions/FunctionForm.tsx
- frontend/src/types/RavenAI/RavenAIFunction.ts
- packages/types/types/RavenAI/RavenAIFunction.ts
- raven/ai/functions.py
- raven/ai/handler.py
- raven/raven_ai/doctype/raven_ai_function/raven_ai_function.json
- raven/raven_ai/doctype/raven_ai_function/raven_ai_function.py
- raven/raven_bot/doctype/raven_bot/raven_bot.py
This PR introduces two new standard AI functions to enhance the Raven AI function calling:
- **Get Value**: Allows AI bots to retrieve values from the system - behaviour similar to frappe's get_value func
- **Set Value**: Allows AI bots to store/update values in the system - behaviour similar to frappe's set_value func
- Added "Get Value" standard function to AI functions
- Added "Set Value" standard function to AI functions
> feat(ai): add new standard functions get_value and set_value

- raven/api/threads.py
- raven/raven_channel_management/doctype/raven_channel_member/raven_channel_member.py
- raven/raven_messaging/doctype/raven_message/raven_message.py
- raven/utils.py
1. Users are added to a thread when they are mentioned - provided that the users are also a part of the main channel
2. When creating a thread from a message with mentions, mentioned users are automatically added to the thread.
> feat: add mentioned users to thread

- raven/ai/agents_integration.py
This PR fixes compatibility issues between the OpenAI Agents SDK and local LLM providers (LM Studio, Ollama, LocalAI, etc.) by implementing proper provider configuration, tool filtering, and conversation history handling. Additionally, it improves performance and conversation memory for all providers.
- **Problem**: The SDK was using `/v1/responses` endpoint (OpenAI-specific) which doesn't exist in local LLM providers
- **Error**: `Error code: 501 - {'error': {'message': 'The /v1/responses endpoint is not yet implemented'}}`
- **Affected providers**: LM Studio, Ollama, LocalAI, and other OpenAI-compatible APIs
- **Solution**: Configure `OpenAIProvider` with `use_responses=False` for Local LLM to use the standard `/v1/chat/completions` endpoint
- **Problem**: Hosted tools (CodeInterpreter, …
> Fix: OpenAI Agents SDK Compatibility with Local LLMs

- raven/api/reactions.py
Create a hook since the reaction is deleted directly in database, so don't trigger in on_trash doctype event.
> feat: create a hook to trigger when reaction is deleted

- frontend/src/App.tsx
- frontend/src/components/feature/channel-settings/delete-channel/DeleteChannelModal.tsx
- frontend/src/components/feature/chat-header/ChannelHeader.tsx
- frontend/src/components/feature/chat-header/DMChannelHeader.tsx
- frontend/src/components/feature/workspaces/WorkspaceActionMenu.tsx
- frontend/src/components/layout/Sidebar/WorkspacesSidebar.tsx
- frontend/src/components/layout/WorkspaceSwitcherGrid.tsx
- frontend/src/pages/ChatSpace.tsx
- frontend/src/pages/ErrorPage.tsx
- frontend/src/pages/settings/AI/ViewBot.tsx
- frontend/src/pages/settings/Settings.tsx
- frontend/src/utils/auth/UserProvider.tsx
- frontend/src/utils/lastVisitedAtoms.ts
Also fixed an issue where if you rename a workspace and then go back to the chat space, it was using the older workspace ID forcing the user to select the workspace again.
> chore(web): use atoms to track last visited workspace and channels

- raven/api/reactions.py
Any message that a user can read, they can reply to. Hence the permission check is on the read permissions on the message.
> feat: allow reacting to messages in accessible threads

- apps/web/eslint.config.js
- apps/web/package.json
- apps/web/src/components/features/ChatInput/ChatInput.tsx
- apps/web/src/components/features/ChatInput/InputFiles.tsx
- apps/web/src/components/features/ChatInput/SendButton.tsx
- apps/web/src/components/features/ChatInput/useFileInput.ts
- apps/web/src/components/ui/circular-progress.tsx
- apps/web/src/components/ui/progress.tsx
- apps/web/src/pages/Channel.tsx
- yarn.lock
Upload files as soon as the user adds them to the chatbox optimistically to avoid waiting. 
If file uploads fail, allow users to remove them. If user decides to cancel an upload, they can delete the file from the server.
TODO: when sending messages, queue up messages with files still not uploaded.
https://github.com/user-attachments/assets/952ce0e2-2688-403c-8ac8-70c725bcac93
> feat(v3): optimistic file uploads
